// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents the state of an account on the ledger.
public struct Account: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The sequence number of this account. This number increments
  /// with each transaction sent by this account.
  public var sequenceNumber: Swift.Int64 = Swift.Int64()

  /// Output only. The primary public key associated with this account, used for
  /// signature verification.
  public var publicKey: Foundation.Data = Foundation.Data()

  /// Output only. The ID of the execution round (similar to block "height") at
  /// which the account information provided is accurate.
  public var roundId: Swift.Int64 = Swift.Int64()

  /// Output only. The account comment stored when this account was created.
  public var comment: Swift.String = Swift.String()

  /// Specific details based on the type of account.
  public var accountDetails: OneOf_AccountDetails? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Account`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Account().with { $0.userDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let userDetails = CodingKeys(stringValue: "userDetails")
    static let accountManagerDetails = CodingKeys(stringValue: "accountManagerDetails")
    static let tokenManagerDetails = CodingKeys(stringValue: "tokenManagerDetails")
    static let contractTokenManagerDetails = CodingKeys(stringValue: "contractTokenManagerDetails")
    static let contractDetails = CodingKeys(stringValue: "contractDetails")
    static let clearinghouseDetails = CodingKeys(stringValue: "clearinghouseDetails")
    static let currencyOperatorDetails = CodingKeys(stringValue: "currencyOperatorDetails")
    static let platformOperatorDetails = CodingKeys(stringValue: "platformOperatorDetails")
    static let sequenceNumber = CodingKeys(stringValue: "sequenceNumber")
    static let publicKey = CodingKeys(stringValue: "publicKey")
    static let roundId = CodingKeys(stringValue: "roundId")
    static let comment = CodingKeys(stringValue: "comment")

    static let _knownKeys: Set<Swift.String> = [
      "userDetails",
      "accountManagerDetails",
      "tokenManagerDetails",
      "contractTokenManagerDetails",
      "contractDetails",
      "clearinghouseDetails",
      "currencyOperatorDetails",
      "platformOperatorDetails",
      "sequenceNumber",
      "publicKey",
      "roundId",
      "comment",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sequenceNumber) {
      self.sequenceNumber = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .publicKey) {
      self.publicKey = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .roundId) {
      self.roundId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .comment) {
      self.comment = value
    }

    var accountDetails: OneOf_AccountDetails? = nil
    let accountDetailsCheckAndSet = {
      if accountDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'accountDetails'"))
      }
      accountDetails = $0
    }
    if let userDetails = try container.decodeIfPresent(UserDetails?.self, forKey: .userDetails) {
      try accountDetailsCheckAndSet(.userDetails(userDetails))
    }
    if let accountManagerDetails = try container.decodeIfPresent(
      AccountManagerDetails?.self, forKey: .accountManagerDetails)
    {
      try accountDetailsCheckAndSet(.accountManagerDetails(accountManagerDetails))
    }
    if let tokenManagerDetails = try container.decodeIfPresent(
      TokenManagerDetails?.self, forKey: .tokenManagerDetails)
    {
      try accountDetailsCheckAndSet(.tokenManagerDetails(tokenManagerDetails))
    }
    if let contractTokenManagerDetails = try container.decodeIfPresent(
      ContractTokenManagerDetails?.self, forKey: .contractTokenManagerDetails)
    {
      try accountDetailsCheckAndSet(.contractTokenManagerDetails(contractTokenManagerDetails))
    }
    if let contractDetails = try container.decodeIfPresent(
      ContractDetails?.self, forKey: .contractDetails)
    {
      try accountDetailsCheckAndSet(.contractDetails(contractDetails))
    }
    if let clearinghouseDetails = try container.decodeIfPresent(
      ClearingHouseDetails?.self, forKey: .clearinghouseDetails)
    {
      try accountDetailsCheckAndSet(.clearinghouseDetails(clearinghouseDetails))
    }
    if let currencyOperatorDetails = try container.decodeIfPresent(
      CurrencyOperatorDetails?.self, forKey: .currencyOperatorDetails)
    {
      try accountDetailsCheckAndSet(.currencyOperatorDetails(currencyOperatorDetails))
    }
    if let platformOperatorDetails = try container.decodeIfPresent(
      PlatformOperatorDetails?.self, forKey: .platformOperatorDetails)
    {
      try accountDetailsCheckAndSet(.platformOperatorDetails(platformOperatorDetails))
    }
    self.accountDetails = accountDetails
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sequenceNumber, forKey: .sequenceNumber)
    try container.encode(self.publicKey, forKey: .publicKey)
    try container.encode(self.roundId, forKey: .roundId)
    try container.encode(self.comment, forKey: .comment)

    if let choice = self.accountDetails {
      switch choice {
      case .userDetails(let value):
        try container.encode(value, forKey: .userDetails)
      case .accountManagerDetails(let value):
        try container.encode(value, forKey: .accountManagerDetails)
      case .tokenManagerDetails(let value):
        try container.encode(value, forKey: .tokenManagerDetails)
      case .contractTokenManagerDetails(let value):
        try container.encode(value, forKey: .contractTokenManagerDetails)
      case .contractDetails(let value):
        try container.encode(value, forKey: .contractDetails)
      case .clearinghouseDetails(let value):
        try container.encode(value, forKey: .clearinghouseDetails)
      case .currencyOperatorDetails(let value):
        try container.encode(value, forKey: .currencyOperatorDetails)
      case .platformOperatorDetails(let value):
        try container.encode(value, forKey: .platformOperatorDetails)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specific details based on the type of account.
  public enum OneOf_AccountDetails: Codable, Equatable, Sendable {
    /// Output only. Details for a standard user account.
    indirect case userDetails(UserDetails?)
    /// Output only. Details for an account manager account.
    indirect case accountManagerDetails(AccountManagerDetails?)
    /// Output only. Details for a token manager account.
    indirect case tokenManagerDetails(TokenManagerDetails?)
    /// Output only. Details for a contract token manager account.
    indirect case contractTokenManagerDetails(ContractTokenManagerDetails?)
    /// Output only. Details for a smart contract account.
    indirect case contractDetails(ContractDetails?)
    /// Output only. Details for a clearinghouse account.
    indirect case clearinghouseDetails(ClearingHouseDetails?)
    /// Output only. Details for a currency operator account.
    indirect case currencyOperatorDetails(CurrencyOperatorDetails?)
    /// Output only. Details for a platform operator account.
    indirect case platformOperatorDetails(PlatformOperatorDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.Account"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
