// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Marks an account as `ACCOUNT_STATUS_ACTIVE`. The sender must be the account
/// manager of the account to activate.
///
/// The account owner can resume normal operations permitted by the roles on the
/// account.
public struct ActivateAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [account_id][google.cloud.universalledger.v1.ActivateAccount.account_id]
  /// instead. The ID of the account to be activated.
  ///
  /// [google.cloud.universalledger.v1.ActivateAccount.account_id]: <doc:ActivateAccount/accountId>
  @available(*, deprecated)
  public var account: Entity? = nil

  /// Optional. The ID of the account to be activated. One of `account` or
  /// `account_id` must be specified. The value is limited to 60 characters.
  public var accountId: Swift.String = Swift.String()

  /// Initialize a new instance of `ActivateAccount`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ActivateAccount().with { $0.account = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ActivateAccount"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
