// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A balance to settle between two token managers.
public struct BalanceToSettle: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Deprecated: Use `balance_payer_id` instead.
  /// The account which owes the balance to be settled.
  @available(*, deprecated)
  public var balancePayer: Entity? = nil

  /// Output only. The ID of the account which owes the balance to be settled.
  public var balancePayerId: Swift.String = Swift.String()

  /// Output only. Deprecated: Use `balance_receiver_id` instead.
  /// The account which is owed the balance to be settled.
  @available(*, deprecated)
  public var balanceReceiver: Entity? = nil

  /// Output only. The ID of the account which is owed the balance to be settled.
  public var balanceReceiverId: Swift.String = Swift.String()

  /// Output only. The balance to settle. Must be positive.
  public var balance: CurrencyValue? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `BalanceToSettle`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BalanceToSettle().with { $0.balancePayer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let balancePayer = CodingKeys(stringValue: "balancePayer")
    static let balancePayerId = CodingKeys(stringValue: "balancePayerId")
    static let balanceReceiver = CodingKeys(stringValue: "balanceReceiver")
    static let balanceReceiverId = CodingKeys(stringValue: "balanceReceiverId")
    static let balance = CodingKeys(stringValue: "balance")

    static let _knownKeys: Set<Swift.String> = [
      "balancePayer",
      "balancePayerId",
      "balanceReceiver",
      "balanceReceiverId",
      "balance",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.balancePayer = try container.decodeIfPresent(Entity.self, forKey: .balancePayer)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .balancePayerId) {
      self.balancePayerId = value
    }
    self.balanceReceiver = try container.decodeIfPresent(Entity.self, forKey: .balanceReceiver)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .balanceReceiverId) {
      self.balanceReceiverId = value
    }
    self.balance = try container.decodeIfPresent(CurrencyValue.self, forKey: .balance)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.balancePayer, forKey: .balancePayer)
    try container.encode(self.balancePayerId, forKey: .balancePayerId)
    try container.encodeIfPresent(self.balanceReceiver, forKey: .balanceReceiver)
    try container.encode(self.balanceReceiverId, forKey: .balanceReceiverId)
    try container.encodeIfPresent(self.balance, forKey: .balance)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.BalanceToSettle"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
