// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A balance to settle between two token managers.
public struct BalanceToSettle: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Deprecated: Use `balance_payer_id` instead.
  /// The account which owes the balance to be settled.
  @available(*, deprecated)
  public var balancePayer: Entity? = nil

  /// Output only. The ID of the account which owes the balance to be settled.
  public var balancePayerId: Swift.String = Swift.String()

  /// Output only. Deprecated: Use `balance_receiver_id` instead.
  /// The account which is owed the balance to be settled.
  @available(*, deprecated)
  public var balanceReceiver: Entity? = nil

  /// Output only. The ID of the account which is owed the balance to be settled.
  public var balanceReceiverId: Swift.String = Swift.String()

  /// Output only. The balance to settle. Must be positive.
  public var balance: CurrencyValue? = nil

  /// Initialize a new instance of `BalanceToSettle`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BalanceToSettle().with { $0.balancePayer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.BalanceToSettle"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
