// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Burns currency tokens. The sender must be a token manager and the account
/// supplying the tokens to burn must additionally sign the transaction.
///
/// The expected flow is that the token manager will have its designated burn
/// account which customers would transfer the tokens to before they are burnt.
/// Alternatively, the customers could directly sign the transaction in which
/// case it would act as an atomic "transfer-and-burn" transaction.
public struct Burn: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The amount to burn.
  public var burnAmount: CurrencyValue? = nil

  /// Optional. Deprecated: Use
  /// [payer_id][google.cloud.universalledger.v1.Burn.payer_id] instead. The
  /// account supplying the tokens to burn. The account must have the
  /// `ROLE_PAYER` enabled on it.
  ///
  /// [google.cloud.universalledger.v1.Burn.payer_id]: <doc:Burn/payerId>
  @available(*, deprecated)
  public var payer: Entity? = nil

  /// Optional. The ID of the account supplying the tokens to burn. The payer
  /// account must have the `ROLE_PAYER` enabled on it. One of `payer` or
  /// `payer_id` must be specified.
  public var payerId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Burn`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Burn().with { $0.burnAmount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let burnAmount = CodingKeys(stringValue: "burnAmount")
    static let payer = CodingKeys(stringValue: "payer")
    static let payerId = CodingKeys(stringValue: "payerId")

    static let _knownKeys: Set<Swift.String> = [
      "burnAmount",
      "payer",
      "payerId",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.burnAmount = try container.decodeIfPresent(CurrencyValue.self, forKey: .burnAmount)
    self.payer = try container.decodeIfPresent(Entity.self, forKey: .payer)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .payerId) {
      self.payerId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.burnAmount, forKey: .burnAmount)
    try container.encodeIfPresent(self.payer, forKey: .payer)
    try container.encode(self.payerId, forKey: .payerId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.Burn"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
