// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Transfers the responsibility of managing a particular account to another
/// manager. The sender must be the current account manager of the account and,
/// to provide consent, the new manager must also sign this transaction.
public struct ChangeAccountManager: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [account_id][google.cloud.universalledger.v1.ChangeAccountManager.account_id]
  /// instead. The ID of the account whose manager is to be changed.
  ///
  /// [google.cloud.universalledger.v1.ChangeAccountManager.account_id]: <doc:ChangeAccountManager/accountId>
  @available(*, deprecated)
  public var account: Entity? = nil

  /// Optional. The ID of the account whose manager is to be changed. One of
  /// `account` or `account_id` must be specified. The value is limited to 60
  /// characters.
  public var accountId: Swift.String = Swift.String()

  /// Optional. Deprecated: Use
  /// [next_manager_id][google.cloud.universalledger.v1.ChangeAccountManager.next_manager_id]
  /// instead. The ID of the new proposed account manager. Validation requires
  /// that the new manager has also signed this transaction.
  ///
  /// [google.cloud.universalledger.v1.ChangeAccountManager.next_manager_id]: <doc:ChangeAccountManager/nextManagerId>
  @available(*, deprecated)
  public var nextManager: Entity? = nil

  /// Optional. The ID of the new proposed account manager. Validation requires
  /// that the new manager has also signed this transaction. One of
  /// `next_manager` or `next_manager_id` must be specified. The value is limited
  /// to 60 characters.
  public var nextManagerId: Swift.String = Swift.String()

  /// Initialize a new instance of `ChangeAccountManager`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChangeAccountManager().with { $0.account = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ChangeAccountManager"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
