// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Transfers the responsibility of managing a particular account to another
/// manager. The sender must be the current account manager of the account and,
/// to provide consent, the new manager must also sign this transaction.
public struct ChangeAccountManager: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The ID of the account whose manager is to be changed.
  /// The value is limited to 60 characters.
  public var accountId: Swift.String = Swift.String()

  /// Required. The ID of the new proposed account manager. Validation requires
  /// that the new manager has also signed this transaction. The value is limited
  /// to 60 characters.
  public var nextManagerId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ChangeAccountManager`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ChangeAccountManager().with { $0.accountId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accountId = CodingKeys(stringValue: "accountId")
    static let nextManagerId = CodingKeys(stringValue: "nextManagerId")

    static let _knownKeys: Set<Swift.String> = [
      "accountId",
      "nextManagerId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accountId) {
      self.accountId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextManagerId) {
      self.nextManagerId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.accountId, forKey: .accountId)
    try container.encode(self.nextManagerId, forKey: .nextManagerId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ChangeAccountManager`: `"type.googleapis.com/google.cloud.universalledger.v1.ChangeAccountManager"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ChangeAccountManager"
  }

  /// Initialize an instance of `ChangeAccountManager` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.universalledger.v1.ChangeAccountManager"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ChangeAccountManager` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
