// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents a transaction initiated by a client.
public struct ClientTransaction: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The ID of the account that is sending this transaction.
  public var senderId: Swift.String = Swift.String()

  /// Optional. The IDs of accounts that, in addition to the sender, have signed
  /// this transaction.
  public var otherSignatoryIds: [Swift.String] = []

  /// Required. A unique, monotonically increasing number, starting from 0.
  ///
  /// This number must be increased by one for each transaction previously
  /// submitted to the network by the same transaction sender.
  ///
  /// Note this does not include any transaction units that may have been
  /// submitted as part of a chain, which must not set a sequence number. But it
  /// does include the sender of the transaction chain itself.
  public var sequenceNumber: Swift.Int64 = Swift.Int64()

  /// Must be set to true if this client transaction is part of a transaction
  /// chain. Otherwise, it must be set to false.
  ///
  /// This is necessary to prevent a signed transaction intended to be part of a
  /// chain from being submitted on its own.
  public var chainedUnit: Swift.Bool = Swift.Bool()

  /// Required. The name of the network this transaction is intended for, such as
  /// `user-testing`. The transaction will be rejected if the name does not
  /// match that of the network processing the transaction.
  public var network: Swift.String = Swift.String()

  /// The client transaction-specific message.
  public var kind: KindOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ClientTransaction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientTransaction().with { $0.operational = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let operational = CodingKeys(stringValue: "operational")
    static let transferPlatformOperatorTransaction = CodingKeys(
      stringValue: "transferPlatformOperatorTransaction")
    static let createCurrencyOperatorTransaction = CodingKeys(
      stringValue: "createCurrencyOperatorTransaction")
    static let transferCurrencyOperatorTransaction = CodingKeys(
      stringValue: "transferCurrencyOperatorTransaction")
    static let createClearinghouseTransaction = CodingKeys(
      stringValue: "createClearinghouseTransaction")
    static let createAccountManagerTransaction = CodingKeys(
      stringValue: "createAccountManagerTransaction")
    static let createTokenManagerTransaction = CodingKeys(
      stringValue: "createTokenManagerTransaction")
    static let increaseTokenIssuanceLimitTransaction = CodingKeys(
      stringValue: "increaseTokenIssuanceLimitTransaction")
    static let decreaseTokenIssuanceLimitTransaction = CodingKeys(
      stringValue: "decreaseTokenIssuanceLimitTransaction")
    static let settlementRequestTransaction = CodingKeys(
      stringValue: "settlementRequestTransaction")
    static let mintTransaction = CodingKeys(stringValue: "mintTransaction")
    static let burnTransaction = CodingKeys(stringValue: "burnTransaction")
    static let createAccountTransaction = CodingKeys(stringValue: "createAccountTransaction")
    static let deactivateAccountTransaction = CodingKeys(
      stringValue: "deactivateAccountTransaction")
    static let activateAccountTransaction = CodingKeys(stringValue: "activateAccountTransaction")
    static let addRolesTransaction = CodingKeys(stringValue: "addRolesTransaction")
    static let removeRolesTransaction = CodingKeys(stringValue: "removeRolesTransaction")
    static let changeAccountManagerTransaction = CodingKeys(
      stringValue: "changeAccountManagerTransaction")
    static let transferTransaction = CodingKeys(stringValue: "transferTransaction")
    static let createContractTransaction = CodingKeys(stringValue: "createContractTransaction")
    static let grantContractPermissionsTransaction = CodingKeys(
      stringValue: "grantContractPermissionsTransaction")
    static let invokeContractMethodTransaction = CodingKeys(
      stringValue: "invokeContractMethodTransaction")
    static let createContractTokenManagerTransaction = CodingKeys(
      stringValue: "createContractTokenManagerTransaction")
    static let transferContractTokenManagerTransaction = CodingKeys(
      stringValue: "transferContractTokenManagerTransaction")
    static let removeSigningPublicKeyTransaction = CodingKeys(
      stringValue: "removeSigningPublicKeyTransaction")
    static let replaceSigningPublicKeyTransaction = CodingKeys(
      stringValue: "replaceSigningPublicKeyTransaction")
    static let chain = CodingKeys(stringValue: "chain")
    static let senderId = CodingKeys(stringValue: "senderId")
    static let otherSignatoryIds = CodingKeys(stringValue: "otherSignatoryIds")
    static let sequenceNumber = CodingKeys(stringValue: "sequenceNumber")
    static let chainedUnit = CodingKeys(stringValue: "chainedUnit")
    static let network = CodingKeys(stringValue: "network")

    static let _knownKeys: Set<Swift.String> = [
      "operational",
      "transferPlatformOperatorTransaction",
      "createCurrencyOperatorTransaction",
      "transferCurrencyOperatorTransaction",
      "createClearinghouseTransaction",
      "createAccountManagerTransaction",
      "createTokenManagerTransaction",
      "increaseTokenIssuanceLimitTransaction",
      "decreaseTokenIssuanceLimitTransaction",
      "settlementRequestTransaction",
      "mintTransaction",
      "burnTransaction",
      "createAccountTransaction",
      "deactivateAccountTransaction",
      "activateAccountTransaction",
      "addRolesTransaction",
      "removeRolesTransaction",
      "changeAccountManagerTransaction",
      "transferTransaction",
      "createContractTransaction",
      "grantContractPermissionsTransaction",
      "invokeContractMethodTransaction",
      "createContractTokenManagerTransaction",
      "transferContractTokenManagerTransaction",
      "removeSigningPublicKeyTransaction",
      "replaceSigningPublicKeyTransaction",
      "chain",
      "senderId",
      "otherSignatoryIds",
      "sequenceNumber",
      "chainedUnit",
      "network",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .senderId) {
      self.senderId = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .otherSignatoryIds) {
      self.otherSignatoryIds = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sequenceNumber) {
      self.sequenceNumber = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .chainedUnit) {
      self.chainedUnit = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }

    var kind: KindOneOf? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let operational = try container.decodeIfPresent(GoogleWKT.WKTAny.self, forKey: .operational)
    {
      try kindCheckAndSet(.operational(operational))
    }
    if let transferPlatformOperatorTransaction = try container.decodeIfPresent(
      TransferPlatformOperator.self, forKey: .transferPlatformOperatorTransaction)
    {
      try kindCheckAndSet(.transferPlatformOperatorTransaction(transferPlatformOperatorTransaction))
    }
    if let createCurrencyOperatorTransaction = try container.decodeIfPresent(
      CreateCurrencyOperator.self, forKey: .createCurrencyOperatorTransaction)
    {
      try kindCheckAndSet(.createCurrencyOperatorTransaction(createCurrencyOperatorTransaction))
    }
    if let transferCurrencyOperatorTransaction = try container.decodeIfPresent(
      TransferCurrencyOperator.self, forKey: .transferCurrencyOperatorTransaction)
    {
      try kindCheckAndSet(.transferCurrencyOperatorTransaction(transferCurrencyOperatorTransaction))
    }
    if let createClearinghouseTransaction = try container.decodeIfPresent(
      CreateClearinghouse.self, forKey: .createClearinghouseTransaction)
    {
      try kindCheckAndSet(.createClearinghouseTransaction(createClearinghouseTransaction))
    }
    if let createAccountManagerTransaction = try container.decodeIfPresent(
      CreateAccountManager.self, forKey: .createAccountManagerTransaction)
    {
      try kindCheckAndSet(.createAccountManagerTransaction(createAccountManagerTransaction))
    }
    if let createTokenManagerTransaction = try container.decodeIfPresent(
      CreateTokenManager.self, forKey: .createTokenManagerTransaction)
    {
      try kindCheckAndSet(.createTokenManagerTransaction(createTokenManagerTransaction))
    }
    if let increaseTokenIssuanceLimitTransaction = try container.decodeIfPresent(
      IncreaseTokenIssuanceLimit.self, forKey: .increaseTokenIssuanceLimitTransaction)
    {
      try kindCheckAndSet(
        .increaseTokenIssuanceLimitTransaction(increaseTokenIssuanceLimitTransaction))
    }
    if let decreaseTokenIssuanceLimitTransaction = try container.decodeIfPresent(
      DecreaseTokenIssuanceLimit.self, forKey: .decreaseTokenIssuanceLimitTransaction)
    {
      try kindCheckAndSet(
        .decreaseTokenIssuanceLimitTransaction(decreaseTokenIssuanceLimitTransaction))
    }
    if let settlementRequestTransaction = try container.decodeIfPresent(
      SettlementRequest.self, forKey: .settlementRequestTransaction)
    {
      try kindCheckAndSet(.settlementRequestTransaction(settlementRequestTransaction))
    }
    if let mintTransaction = try container.decodeIfPresent(Mint.self, forKey: .mintTransaction) {
      try kindCheckAndSet(.mintTransaction(mintTransaction))
    }
    if let burnTransaction = try container.decodeIfPresent(Burn.self, forKey: .burnTransaction) {
      try kindCheckAndSet(.burnTransaction(burnTransaction))
    }
    if let createAccountTransaction = try container.decodeIfPresent(
      CreateAccount.self, forKey: .createAccountTransaction)
    {
      try kindCheckAndSet(.createAccountTransaction(createAccountTransaction))
    }
    if let deactivateAccountTransaction = try container.decodeIfPresent(
      DeactivateAccount.self, forKey: .deactivateAccountTransaction)
    {
      try kindCheckAndSet(.deactivateAccountTransaction(deactivateAccountTransaction))
    }
    if let activateAccountTransaction = try container.decodeIfPresent(
      ActivateAccount.self, forKey: .activateAccountTransaction)
    {
      try kindCheckAndSet(.activateAccountTransaction(activateAccountTransaction))
    }
    if let addRolesTransaction = try container.decodeIfPresent(
      AddRoles.self, forKey: .addRolesTransaction)
    {
      try kindCheckAndSet(.addRolesTransaction(addRolesTransaction))
    }
    if let removeRolesTransaction = try container.decodeIfPresent(
      RemoveRoles.self, forKey: .removeRolesTransaction)
    {
      try kindCheckAndSet(.removeRolesTransaction(removeRolesTransaction))
    }
    if let changeAccountManagerTransaction = try container.decodeIfPresent(
      ChangeAccountManager.self, forKey: .changeAccountManagerTransaction)
    {
      try kindCheckAndSet(.changeAccountManagerTransaction(changeAccountManagerTransaction))
    }
    if let transferTransaction = try container.decodeIfPresent(
      Transfer.self, forKey: .transferTransaction)
    {
      try kindCheckAndSet(.transferTransaction(transferTransaction))
    }
    if let createContractTransaction = try container.decodeIfPresent(
      CreateContract.self, forKey: .createContractTransaction)
    {
      try kindCheckAndSet(.createContractTransaction(createContractTransaction))
    }
    if let grantContractPermissionsTransaction = try container.decodeIfPresent(
      GrantContractPermissions.self, forKey: .grantContractPermissionsTransaction)
    {
      try kindCheckAndSet(.grantContractPermissionsTransaction(grantContractPermissionsTransaction))
    }
    if let invokeContractMethodTransaction = try container.decodeIfPresent(
      InvokeContractMethod.self, forKey: .invokeContractMethodTransaction)
    {
      try kindCheckAndSet(.invokeContractMethodTransaction(invokeContractMethodTransaction))
    }
    if let createContractTokenManagerTransaction = try container.decodeIfPresent(
      CreateContractTokenManager.self, forKey: .createContractTokenManagerTransaction)
    {
      try kindCheckAndSet(
        .createContractTokenManagerTransaction(createContractTokenManagerTransaction))
    }
    if let transferContractTokenManagerTransaction = try container.decodeIfPresent(
      TransferContractTokenManager.self, forKey: .transferContractTokenManagerTransaction)
    {
      try kindCheckAndSet(
        .transferContractTokenManagerTransaction(transferContractTokenManagerTransaction))
    }
    if let removeSigningPublicKeyTransaction = try container.decodeIfPresent(
      RemoveSigningPublicKey.self, forKey: .removeSigningPublicKeyTransaction)
    {
      try kindCheckAndSet(.removeSigningPublicKeyTransaction(removeSigningPublicKeyTransaction))
    }
    if let replaceSigningPublicKeyTransaction = try container.decodeIfPresent(
      ReplaceSigningPublicKey.self, forKey: .replaceSigningPublicKeyTransaction)
    {
      try kindCheckAndSet(.replaceSigningPublicKeyTransaction(replaceSigningPublicKeyTransaction))
    }
    if let chain = try container.decodeIfPresent(TransactionChain.self, forKey: .chain) {
      try kindCheckAndSet(.chain(chain))
    }
    self.kind = kind
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.senderId, forKey: .senderId)
    try container.encode(self.otherSignatoryIds, forKey: .otherSignatoryIds)
    try container.encode(self.sequenceNumber, forKey: .sequenceNumber)
    try container.encode(self.chainedUnit, forKey: .chainedUnit)
    try container.encode(self.network, forKey: .network)

    if let choice = self.kind {
      switch choice {
      case .operational(let value):
        try container.encode(value, forKey: .operational)
      case .transferPlatformOperatorTransaction(let value):
        try container.encode(value, forKey: .transferPlatformOperatorTransaction)
      case .createCurrencyOperatorTransaction(let value):
        try container.encode(value, forKey: .createCurrencyOperatorTransaction)
      case .transferCurrencyOperatorTransaction(let value):
        try container.encode(value, forKey: .transferCurrencyOperatorTransaction)
      case .createClearinghouseTransaction(let value):
        try container.encode(value, forKey: .createClearinghouseTransaction)
      case .createAccountManagerTransaction(let value):
        try container.encode(value, forKey: .createAccountManagerTransaction)
      case .createTokenManagerTransaction(let value):
        try container.encode(value, forKey: .createTokenManagerTransaction)
      case .increaseTokenIssuanceLimitTransaction(let value):
        try container.encode(value, forKey: .increaseTokenIssuanceLimitTransaction)
      case .decreaseTokenIssuanceLimitTransaction(let value):
        try container.encode(value, forKey: .decreaseTokenIssuanceLimitTransaction)
      case .settlementRequestTransaction(let value):
        try container.encode(value, forKey: .settlementRequestTransaction)
      case .mintTransaction(let value):
        try container.encode(value, forKey: .mintTransaction)
      case .burnTransaction(let value):
        try container.encode(value, forKey: .burnTransaction)
      case .createAccountTransaction(let value):
        try container.encode(value, forKey: .createAccountTransaction)
      case .deactivateAccountTransaction(let value):
        try container.encode(value, forKey: .deactivateAccountTransaction)
      case .activateAccountTransaction(let value):
        try container.encode(value, forKey: .activateAccountTransaction)
      case .addRolesTransaction(let value):
        try container.encode(value, forKey: .addRolesTransaction)
      case .removeRolesTransaction(let value):
        try container.encode(value, forKey: .removeRolesTransaction)
      case .changeAccountManagerTransaction(let value):
        try container.encode(value, forKey: .changeAccountManagerTransaction)
      case .transferTransaction(let value):
        try container.encode(value, forKey: .transferTransaction)
      case .createContractTransaction(let value):
        try container.encode(value, forKey: .createContractTransaction)
      case .grantContractPermissionsTransaction(let value):
        try container.encode(value, forKey: .grantContractPermissionsTransaction)
      case .invokeContractMethodTransaction(let value):
        try container.encode(value, forKey: .invokeContractMethodTransaction)
      case .createContractTokenManagerTransaction(let value):
        try container.encode(value, forKey: .createContractTokenManagerTransaction)
      case .transferContractTokenManagerTransaction(let value):
        try container.encode(value, forKey: .transferContractTokenManagerTransaction)
      case .removeSigningPublicKeyTransaction(let value):
        try container.encode(value, forKey: .removeSigningPublicKeyTransaction)
      case .replaceSigningPublicKeyTransaction(let value):
        try container.encode(value, forKey: .replaceSigningPublicKeyTransaction)
      case .chain(let value):
        try container.encode(value, forKey: .chain)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The client transaction-specific message.
  public enum KindOneOf: Codable, Equatable, Sendable {
    /// Optional. An operational transaction message. Note this can only be sent
    /// by the platform operator. Should be any one of:
    ///
    /// <!--
    /// clang-format off
    /// -->
    /// - [CreateSnapshot][google.cloud.universalledger.v1.CreateSnapshot]
    /// <!--
    /// clang-format on
    /// -->
    ///
    /// [google.cloud.universalledger.v1.CreateSnapshot]: <doc:CreateSnapshot>
    indirect case operational(GoogleWKT.WKTAny)
    /// Optional. Message for transferring the platform operator role to a new
    /// account.
    indirect case transferPlatformOperatorTransaction(TransferPlatformOperator)
    /// Optional. Message for creating a new currency operator.
    indirect case createCurrencyOperatorTransaction(CreateCurrencyOperator)
    /// Optional. Message for transferring the currency operator role to a new
    /// account.
    indirect case transferCurrencyOperatorTransaction(TransferCurrencyOperator)
    /// Optional. Message for creating a new clearinghouse.
    indirect case createClearinghouseTransaction(CreateClearinghouse)
    /// Optional. Message for creating a new account manager.
    indirect case createAccountManagerTransaction(CreateAccountManager)
    /// Optional. Message for creating a new token manager associated to the
    /// currency of the operator sending the request.
    indirect case createTokenManagerTransaction(CreateTokenManager)
    /// Optional. Notifies the network that the target account has deposited
    /// reserve funds and increases its token issuance limit.
    indirect case increaseTokenIssuanceLimitTransaction(IncreaseTokenIssuanceLimit)
    /// Optional. Notifies the network that the target account wishes to withdraw
    /// reserve funds and decreases its token issuance limit.
    indirect case decreaseTokenIssuanceLimitTransaction(DecreaseTokenIssuanceLimit)
    /// Optional. Message for initiating a settlement operation.
    indirect case settlementRequestTransaction(SettlementRequest)
    /// Optional. Message for minting currency tokens and transferring them to an
    /// account.
    indirect case mintTransaction(Mint)
    /// Optional. Message for burning currency tokens from an account.
    indirect case burnTransaction(Burn)
    /// Optional. Message for creating a new user account.
    indirect case createAccountTransaction(CreateAccount)
    /// Optional. Message for deactivating a user account.
    indirect case deactivateAccountTransaction(DeactivateAccount)
    /// Optional. Message for activating a user account.
    indirect case activateAccountTransaction(ActivateAccount)
    /// Optional. Message for adding roles to an account.
    indirect case addRolesTransaction(AddRoles)
    /// Optional. Message for removing roles from an account.
    indirect case removeRolesTransaction(RemoveRoles)
    /// Optional. Message for changing the account manager of an account.
    indirect case changeAccountManagerTransaction(ChangeAccountManager)
    /// Optional. Message for transferring tokens from one user account to
    /// another.
    indirect case transferTransaction(Transfer)
    /// Optional. Message for creating a new contract on the ledger.
    indirect case createContractTransaction(CreateContract)
    /// Optional. Message for granting permissions to a contract.
    indirect case grantContractPermissionsTransaction(GrantContractPermissions)
    /// Optional. Message for invoking the execution of a contract method.
    indirect case invokeContractMethodTransaction(InvokeContractMethod)
    /// Optional. Message for creating a new token manager associated to the
    /// currency of the operator sending the request.
    indirect case createContractTokenManagerTransaction(CreateContractTokenManager)
    /// Optional. Message for transferring the token manager role for a currency
    /// from one account to another.
    indirect case transferContractTokenManagerTransaction(TransferContractTokenManager)
    /// Optional. Message for removing an account signing key.
    indirect case removeSigningPublicKeyTransaction(RemoveSigningPublicKey)
    /// Optional. Message for replacing an account signing key.
    indirect case replaceSigningPublicKeyTransaction(ReplaceSigningPublicKey)
    /// Optional. Message for a transaction chain including multiple transaction
    /// units to execute in sequence.
    indirect case chain(TransactionChain)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ClientTransaction"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
