// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a transaction initiated by a client.
public struct ClientTransaction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The transaction sender.
  /// Deprecated: Use
  /// [sender_id][google.cloud.universalledger.v1.ClientTransaction.sender_id]
  /// instead.
  ///
  /// [google.cloud.universalledger.v1.ClientTransaction.sender_id]: <doc:ClientTransaction/senderId>
  @available(*, deprecated)
  public var source: Entity? = nil

  /// Optional. The ID of the account that is sending this transaction.
  /// One of `source` or `sender_id` must be set.
  public var senderId: Swift.String = Swift.String()

  /// Optional. Accounts that, in addition to the sender, have signed this
  /// transaction. Deprecated: Use
  /// [other_signatory_ids][google.cloud.universalledger.v1.ClientTransaction.other_signatory_ids]
  /// instead.
  ///
  /// [google.cloud.universalledger.v1.ClientTransaction.other_signatory_ids]: <doc:ClientTransaction/otherSignatoryIds>
  @available(*, deprecated)
  public var signatories: [Entity] = []

  /// Optional. The IDs of accounts that, in addition to the sender, have signed
  /// this transaction.
  public var otherSignatoryIds: [Swift.String] = []

  /// Required. A unique, monotonically increasing number, starting from 0.
  ///
  /// This number must be increased by one for each transaction previously
  /// submitted to the network by the same transaction sender.
  ///
  /// Note this does not include any transaction units that may have been
  /// submitted as part of a chain, which must not set a sequence number. But it
  /// does include the sender of the transaction chain itself.
  public var sequenceNumber: Swift.Int64 = Swift.Int64()

  /// Must be set to true if this client transaction is part of a transaction
  /// chain. Otherwise, it must be set to false.
  ///
  /// This is necessary to prevent a signed transaction intended to be part of a
  /// chain from being submitted on its own.
  public var chainedUnit: Swift.Bool = Swift.Bool()

  /// The client transaction-specific message.
  public var kind: OneOf_Kind? = nil

  /// Initialize a new instance of `ClientTransaction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientTransaction().with { $0.app = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case app = "app"
    case operational = "operational"
    case transferPlatformOperatorTransaction = "transferPlatformOperatorTransaction"
    case createCurrencyOperatorTransaction = "createCurrencyOperatorTransaction"
    case transferCurrencyOperatorTransaction = "transferCurrencyOperatorTransaction"
    case createClearinghouseTransaction = "createClearinghouseTransaction"
    case createAccountManagerTransaction = "createAccountManagerTransaction"
    case createTokenManagerTransaction = "createTokenManagerTransaction"
    case increaseTokenIssuanceLimitTransaction = "increaseTokenIssuanceLimitTransaction"
    case decreaseTokenIssuanceLimitTransaction = "decreaseTokenIssuanceLimitTransaction"
    case settlementRequestTransaction = "settlementRequestTransaction"
    case mintTransaction = "mintTransaction"
    case burnTransaction = "burnTransaction"
    case createAccountTransaction = "createAccountTransaction"
    case deactivateAccountTransaction = "deactivateAccountTransaction"
    case activateAccountTransaction = "activateAccountTransaction"
    case addRolesTransaction = "addRolesTransaction"
    case removeRolesTransaction = "removeRolesTransaction"
    case changeAccountManagerTransaction = "changeAccountManagerTransaction"
    case transferTransaction = "transferTransaction"
    case createContractTransaction = "createContractTransaction"
    case grantContractPermissionsTransaction = "grantContractPermissionsTransaction"
    case invokeContractMethodTransaction = "invokeContractMethodTransaction"
    case createContractTokenManagerTransaction = "createContractTokenManagerTransaction"
    case transferContractTokenManagerTransaction = "transferContractTokenManagerTransaction"
    case removeSigningPublicKeyTransaction = "removeSigningPublicKeyTransaction"
    case replaceSigningPublicKeyTransaction = "replaceSigningPublicKeyTransaction"
    case chain = "chain"
    case source = "source"
    case senderId = "senderId"
    case signatories = "signatories"
    case otherSignatoryIds = "otherSignatoryIds"
    case sequenceNumber = "sequenceNumber"
    case chainedUnit = "chainedUnit"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.source = try container.decodeIfPresent(Entity.self, forKey: .source)
    self.senderId = try container.decode(Swift.String.self, forKey: .senderId)
    self.signatories = try container.decode([Entity].self, forKey: .signatories)
    self.otherSignatoryIds = try container.decode([Swift.String].self, forKey: .otherSignatoryIds)
    self.sequenceNumber = try container.decode(Swift.Int64.self, forKey: .sequenceNumber)
    self.chainedUnit = try container.decode(Swift.Bool.self, forKey: .chainedUnit)

    var kind: OneOf_Kind? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let app = try container.decodeIfPresent(GoogleCloudWkt.`Any`?.self, forKey: .app) {
      try kindCheckAndSet(.app(app))
    }
    if let operational = try container.decodeIfPresent(
      GoogleCloudWkt.`Any`?.self, forKey: .operational)
    {
      try kindCheckAndSet(.operational(operational))
    }
    if let transferPlatformOperatorTransaction = try container.decodeIfPresent(
      TransferPlatformOperator?.self, forKey: .transferPlatformOperatorTransaction)
    {
      try kindCheckAndSet(.transferPlatformOperatorTransaction(transferPlatformOperatorTransaction))
    }
    if let createCurrencyOperatorTransaction = try container.decodeIfPresent(
      CreateCurrencyOperator?.self, forKey: .createCurrencyOperatorTransaction)
    {
      try kindCheckAndSet(.createCurrencyOperatorTransaction(createCurrencyOperatorTransaction))
    }
    if let transferCurrencyOperatorTransaction = try container.decodeIfPresent(
      TransferCurrencyOperator?.self, forKey: .transferCurrencyOperatorTransaction)
    {
      try kindCheckAndSet(.transferCurrencyOperatorTransaction(transferCurrencyOperatorTransaction))
    }
    if let createClearinghouseTransaction = try container.decodeIfPresent(
      CreateClearinghouse?.self, forKey: .createClearinghouseTransaction)
    {
      try kindCheckAndSet(.createClearinghouseTransaction(createClearinghouseTransaction))
    }
    if let createAccountManagerTransaction = try container.decodeIfPresent(
      CreateAccountManager?.self, forKey: .createAccountManagerTransaction)
    {
      try kindCheckAndSet(.createAccountManagerTransaction(createAccountManagerTransaction))
    }
    if let createTokenManagerTransaction = try container.decodeIfPresent(
      CreateTokenManager?.self, forKey: .createTokenManagerTransaction)
    {
      try kindCheckAndSet(.createTokenManagerTransaction(createTokenManagerTransaction))
    }
    if let increaseTokenIssuanceLimitTransaction = try container.decodeIfPresent(
      IncreaseTokenIssuanceLimit?.self, forKey: .increaseTokenIssuanceLimitTransaction)
    {
      try kindCheckAndSet(
        .increaseTokenIssuanceLimitTransaction(increaseTokenIssuanceLimitTransaction))
    }
    if let decreaseTokenIssuanceLimitTransaction = try container.decodeIfPresent(
      DecreaseTokenIssuanceLimit?.self, forKey: .decreaseTokenIssuanceLimitTransaction)
    {
      try kindCheckAndSet(
        .decreaseTokenIssuanceLimitTransaction(decreaseTokenIssuanceLimitTransaction))
    }
    if let settlementRequestTransaction = try container.decodeIfPresent(
      SettlementRequest?.self, forKey: .settlementRequestTransaction)
    {
      try kindCheckAndSet(.settlementRequestTransaction(settlementRequestTransaction))
    }
    if let mintTransaction = try container.decodeIfPresent(Mint?.self, forKey: .mintTransaction) {
      try kindCheckAndSet(.mintTransaction(mintTransaction))
    }
    if let burnTransaction = try container.decodeIfPresent(Burn?.self, forKey: .burnTransaction) {
      try kindCheckAndSet(.burnTransaction(burnTransaction))
    }
    if let createAccountTransaction = try container.decodeIfPresent(
      CreateAccount?.self, forKey: .createAccountTransaction)
    {
      try kindCheckAndSet(.createAccountTransaction(createAccountTransaction))
    }
    if let deactivateAccountTransaction = try container.decodeIfPresent(
      DeactivateAccount?.self, forKey: .deactivateAccountTransaction)
    {
      try kindCheckAndSet(.deactivateAccountTransaction(deactivateAccountTransaction))
    }
    if let activateAccountTransaction = try container.decodeIfPresent(
      ActivateAccount?.self, forKey: .activateAccountTransaction)
    {
      try kindCheckAndSet(.activateAccountTransaction(activateAccountTransaction))
    }
    if let addRolesTransaction = try container.decodeIfPresent(
      AddRoles?.self, forKey: .addRolesTransaction)
    {
      try kindCheckAndSet(.addRolesTransaction(addRolesTransaction))
    }
    if let removeRolesTransaction = try container.decodeIfPresent(
      RemoveRoles?.self, forKey: .removeRolesTransaction)
    {
      try kindCheckAndSet(.removeRolesTransaction(removeRolesTransaction))
    }
    if let changeAccountManagerTransaction = try container.decodeIfPresent(
      ChangeAccountManager?.self, forKey: .changeAccountManagerTransaction)
    {
      try kindCheckAndSet(.changeAccountManagerTransaction(changeAccountManagerTransaction))
    }
    if let transferTransaction = try container.decodeIfPresent(
      Transfer?.self, forKey: .transferTransaction)
    {
      try kindCheckAndSet(.transferTransaction(transferTransaction))
    }
    if let createContractTransaction = try container.decodeIfPresent(
      CreateContract?.self, forKey: .createContractTransaction)
    {
      try kindCheckAndSet(.createContractTransaction(createContractTransaction))
    }
    if let grantContractPermissionsTransaction = try container.decodeIfPresent(
      GrantContractPermissions?.self, forKey: .grantContractPermissionsTransaction)
    {
      try kindCheckAndSet(.grantContractPermissionsTransaction(grantContractPermissionsTransaction))
    }
    if let invokeContractMethodTransaction = try container.decodeIfPresent(
      InvokeContractMethod?.self, forKey: .invokeContractMethodTransaction)
    {
      try kindCheckAndSet(.invokeContractMethodTransaction(invokeContractMethodTransaction))
    }
    if let createContractTokenManagerTransaction = try container.decodeIfPresent(
      CreateContractTokenManager?.self, forKey: .createContractTokenManagerTransaction)
    {
      try kindCheckAndSet(
        .createContractTokenManagerTransaction(createContractTokenManagerTransaction))
    }
    if let transferContractTokenManagerTransaction = try container.decodeIfPresent(
      TransferContractTokenManager?.self, forKey: .transferContractTokenManagerTransaction)
    {
      try kindCheckAndSet(
        .transferContractTokenManagerTransaction(transferContractTokenManagerTransaction))
    }
    if let removeSigningPublicKeyTransaction = try container.decodeIfPresent(
      RemoveSigningPublicKey?.self, forKey: .removeSigningPublicKeyTransaction)
    {
      try kindCheckAndSet(.removeSigningPublicKeyTransaction(removeSigningPublicKeyTransaction))
    }
    if let replaceSigningPublicKeyTransaction = try container.decodeIfPresent(
      ReplaceSigningPublicKey?.self, forKey: .replaceSigningPublicKeyTransaction)
    {
      try kindCheckAndSet(.replaceSigningPublicKeyTransaction(replaceSigningPublicKeyTransaction))
    }
    if let chain = try container.decodeIfPresent(TransactionChain?.self, forKey: .chain) {
      try kindCheckAndSet(.chain(chain))
    }
    self.kind = kind
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.source, forKey: .source)
    try container.encode(self.senderId, forKey: .senderId)
    try container.encode(self.signatories, forKey: .signatories)
    try container.encode(self.otherSignatoryIds, forKey: .otherSignatoryIds)
    try container.encode(self.sequenceNumber, forKey: .sequenceNumber)
    try container.encode(self.chainedUnit, forKey: .chainedUnit)

    if let choice = self.kind {
      switch choice {
      case .app(let value):
        try container.encode(value, forKey: .app)
      case .operational(let value):
        try container.encode(value, forKey: .operational)
      case .transferPlatformOperatorTransaction(let value):
        try container.encode(value, forKey: .transferPlatformOperatorTransaction)
      case .createCurrencyOperatorTransaction(let value):
        try container.encode(value, forKey: .createCurrencyOperatorTransaction)
      case .transferCurrencyOperatorTransaction(let value):
        try container.encode(value, forKey: .transferCurrencyOperatorTransaction)
      case .createClearinghouseTransaction(let value):
        try container.encode(value, forKey: .createClearinghouseTransaction)
      case .createAccountManagerTransaction(let value):
        try container.encode(value, forKey: .createAccountManagerTransaction)
      case .createTokenManagerTransaction(let value):
        try container.encode(value, forKey: .createTokenManagerTransaction)
      case .increaseTokenIssuanceLimitTransaction(let value):
        try container.encode(value, forKey: .increaseTokenIssuanceLimitTransaction)
      case .decreaseTokenIssuanceLimitTransaction(let value):
        try container.encode(value, forKey: .decreaseTokenIssuanceLimitTransaction)
      case .settlementRequestTransaction(let value):
        try container.encode(value, forKey: .settlementRequestTransaction)
      case .mintTransaction(let value):
        try container.encode(value, forKey: .mintTransaction)
      case .burnTransaction(let value):
        try container.encode(value, forKey: .burnTransaction)
      case .createAccountTransaction(let value):
        try container.encode(value, forKey: .createAccountTransaction)
      case .deactivateAccountTransaction(let value):
        try container.encode(value, forKey: .deactivateAccountTransaction)
      case .activateAccountTransaction(let value):
        try container.encode(value, forKey: .activateAccountTransaction)
      case .addRolesTransaction(let value):
        try container.encode(value, forKey: .addRolesTransaction)
      case .removeRolesTransaction(let value):
        try container.encode(value, forKey: .removeRolesTransaction)
      case .changeAccountManagerTransaction(let value):
        try container.encode(value, forKey: .changeAccountManagerTransaction)
      case .transferTransaction(let value):
        try container.encode(value, forKey: .transferTransaction)
      case .createContractTransaction(let value):
        try container.encode(value, forKey: .createContractTransaction)
      case .grantContractPermissionsTransaction(let value):
        try container.encode(value, forKey: .grantContractPermissionsTransaction)
      case .invokeContractMethodTransaction(let value):
        try container.encode(value, forKey: .invokeContractMethodTransaction)
      case .createContractTokenManagerTransaction(let value):
        try container.encode(value, forKey: .createContractTokenManagerTransaction)
      case .transferContractTokenManagerTransaction(let value):
        try container.encode(value, forKey: .transferContractTokenManagerTransaction)
      case .removeSigningPublicKeyTransaction(let value):
        try container.encode(value, forKey: .removeSigningPublicKeyTransaction)
      case .replaceSigningPublicKeyTransaction(let value):
        try container.encode(value, forKey: .replaceSigningPublicKeyTransaction)
      case .chain(let value):
        try container.encode(value, forKey: .chain)
      }
    }
  }

  /// The client transaction-specific message.
  public enum OneOf_Kind: Codable, Equatable, Sendable {
    /// Optional. Deprecated: Use one of the message specific fields instead.
    /// A client transaction-specific message. Should be any one of:
    ///
    /// <!--
    /// clang-format off
    /// -->
    /// - [TransferPlatformOperator][google.cloud.universalledger.v1.TransferPlatformOperator]
    /// - [CreateCurrencyOperator][google.cloud.universalledger.v1.CreateCurrencyOperator]
    /// - [TransferCurrencyOperator][google.cloud.universalledger.v1.TransferCurrencyOperator]
    /// - [CreateAccountManager][google.cloud.universalledger.v1.CreateAccountManager]
    /// - [CreateTokenManager][google.cloud.universalledger.v1.CreateTokenManager]
    /// - [CreateClearinghouse][google.cloud.universalledger.v1.CreateClearinghouse]
    /// - [IncreaseTokenIssuanceLimit][google.cloud.universalledger.v1.IncreaseTokenIssuanceLimit]
    /// - [DecreaseTokenIssuanceLimit][google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit]
    /// - [SettlementRequest][google.cloud.universalledger.v1.SettlementRequest]
    /// - [Mint][google.cloud.universalledger.v1.Mint]
    /// - [Burn][google.cloud.universalledger.v1.Burn]
    /// - [CreateAccount][google.cloud.universalledger.v1.CreateAccount]
    /// - [DeactivateAccount][google.cloud.universalledger.v1.DeactivateAccount]
    /// - [ActivateAccount][google.cloud.universalledger.v1.ActivateAccount]
    /// - [AddRoles][google.cloud.universalledger.v1.AddRoles]
    /// - [RemoveRoles][google.cloud.universalledger.v1.RemoveRoles]
    /// - [ChangeAccountManager][google.cloud.universalledger.v1.ChangeAccountManager]
    /// - [Transfer][google.cloud.universalledger.v1.Transfer]
    /// - [CreateContract][google.cloud.universalledger.v1.CreateContract]
    /// - [GrantContractPermissions][google.cloud.universalledger.v1.GrantContractPermissions]
    /// - [InvokeContractMethod][google.cloud.universalledger.v1.InvokeContractMethod]
    /// - [CreateContractTokenManager][google.cloud.universalledger.v1.CreateContractTokenManager]
    /// - [TransferContractTokenManager][google.cloud.universalledger.v1.TransferContractTokenManager]
    /// <!--
    /// clang-format on
    /// -->
    ///
    /// [google.cloud.universalledger.v1.ActivateAccount]: <doc:ActivateAccount>
    /// [google.cloud.universalledger.v1.AddRoles]: <doc:AddRoles>
    /// [google.cloud.universalledger.v1.Burn]: <doc:Burn>
    /// [google.cloud.universalledger.v1.ChangeAccountManager]: <doc:ChangeAccountManager>
    /// [google.cloud.universalledger.v1.CreateAccount]: <doc:CreateAccount>
    /// [google.cloud.universalledger.v1.CreateAccountManager]: <doc:CreateAccountManager>
    /// [google.cloud.universalledger.v1.CreateClearinghouse]: <doc:CreateClearinghouse>
    /// [google.cloud.universalledger.v1.CreateContract]: <doc:CreateContract>
    /// [google.cloud.universalledger.v1.CreateContractTokenManager]: <doc:CreateContractTokenManager>
    /// [google.cloud.universalledger.v1.CreateCurrencyOperator]: <doc:CreateCurrencyOperator>
    /// [google.cloud.universalledger.v1.CreateTokenManager]: <doc:CreateTokenManager>
    /// [google.cloud.universalledger.v1.DeactivateAccount]: <doc:DeactivateAccount>
    /// [google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit]: <doc:DecreaseTokenIssuanceLimit>
    /// [google.cloud.universalledger.v1.GrantContractPermissions]: <doc:GrantContractPermissions>
    /// [google.cloud.universalledger.v1.IncreaseTokenIssuanceLimit]: <doc:IncreaseTokenIssuanceLimit>
    /// [google.cloud.universalledger.v1.InvokeContractMethod]: <doc:InvokeContractMethod>
    /// [google.cloud.universalledger.v1.Mint]: <doc:Mint>
    /// [google.cloud.universalledger.v1.RemoveRoles]: <doc:RemoveRoles>
    /// [google.cloud.universalledger.v1.SettlementRequest]: <doc:SettlementRequest>
    /// [google.cloud.universalledger.v1.Transfer]: <doc:Transfer>
    /// [google.cloud.universalledger.v1.TransferContractTokenManager]: <doc:TransferContractTokenManager>
    /// [google.cloud.universalledger.v1.TransferCurrencyOperator]: <doc:TransferCurrencyOperator>
    /// [google.cloud.universalledger.v1.TransferPlatformOperator]: <doc:TransferPlatformOperator>
    @available(*, deprecated)
    indirect case app(GoogleCloudWkt.`Any`?)
    /// Optional. An operational transaction message. Note this can only be sent
    /// by the platform operator. Should be any one of:
    ///
    /// <!--
    /// clang-format off
    /// -->
    /// - [CreateSnapshot][google.cloud.universalledger.v1.CreateSnapshot]
    /// <!--
    /// clang-format on
    /// -->
    ///
    /// [google.cloud.universalledger.v1.CreateSnapshot]: <doc:CreateSnapshot>
    indirect case operational(GoogleCloudWkt.`Any`?)
    /// Optional. Message for transferring the platform operator role to a new
    /// account.
    indirect case transferPlatformOperatorTransaction(TransferPlatformOperator?)
    /// Optional. Message for creating a new currency operator.
    indirect case createCurrencyOperatorTransaction(CreateCurrencyOperator?)
    /// Optional. Message for transferring the currency operator role to a new
    /// account.
    indirect case transferCurrencyOperatorTransaction(TransferCurrencyOperator?)
    /// Optional. Message for creating a new clearinghouse.
    indirect case createClearinghouseTransaction(CreateClearinghouse?)
    /// Optional. Message for creating a new account manager.
    indirect case createAccountManagerTransaction(CreateAccountManager?)
    /// Optional. Message for creating a new token manager associated to the
    /// currency of the operator sending the request.
    indirect case createTokenManagerTransaction(CreateTokenManager?)
    /// Optional. Notifies the network that the target account has deposited
    /// reserve funds and increases its token issuance limit.
    indirect case increaseTokenIssuanceLimitTransaction(IncreaseTokenIssuanceLimit?)
    /// Optional. Notifies the network that the target account wishes to withdraw
    /// reserve funds and decreases its token issuance limit.
    indirect case decreaseTokenIssuanceLimitTransaction(DecreaseTokenIssuanceLimit?)
    /// Optional. Message for initiating a settlement operation.
    indirect case settlementRequestTransaction(SettlementRequest?)
    /// Optional. Message for minting currency tokens and transferring them to an
    /// account.
    indirect case mintTransaction(Mint?)
    /// Optional. Message for burning currency tokens from an account.
    indirect case burnTransaction(Burn?)
    /// Optional. Message for creating a new user account.
    indirect case createAccountTransaction(CreateAccount?)
    /// Optional. Message for deactivating a user account.
    indirect case deactivateAccountTransaction(DeactivateAccount?)
    /// Optional. Message for activating a user account.
    indirect case activateAccountTransaction(ActivateAccount?)
    /// Optional. Message for adding roles to an account.
    indirect case addRolesTransaction(AddRoles?)
    /// Optional. Message for removing roles from an account.
    indirect case removeRolesTransaction(RemoveRoles?)
    /// Optional. Message for changing the account manager of an account.
    indirect case changeAccountManagerTransaction(ChangeAccountManager?)
    /// Optional. Message for transferring tokens from one user account to
    /// another.
    indirect case transferTransaction(Transfer?)
    /// Optional. Message for creating a new contract on the ledger.
    indirect case createContractTransaction(CreateContract?)
    /// Optional. Message for granting permissions to a contract.
    indirect case grantContractPermissionsTransaction(GrantContractPermissions?)
    /// Optional. Message for invoking the execution of a contract method.
    indirect case invokeContractMethodTransaction(InvokeContractMethod?)
    /// Optional. Message for creating a new token manager associated to the
    /// currency of the operator sending the request.
    indirect case createContractTokenManagerTransaction(CreateContractTokenManager?)
    /// Optional. Message for transferring the token manager role for a currency
    /// from one account to another.
    indirect case transferContractTokenManagerTransaction(TransferContractTokenManager?)
    /// Optional. Message for removing an account signing key.
    indirect case removeSigningPublicKeyTransaction(RemoveSigningPublicKey?)
    /// Optional. Message for replacing an account signing key.
    indirect case replaceSigningPublicKeyTransaction(ReplaceSigningPublicKey?)
    /// Optional. Message for a transaction chain including multiple transaction
    /// units to execute in sequence.
    indirect case chain(TransactionChain?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ClientTransaction"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
