// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details specific to a Contract Token Manager.
public struct ContractTokenManagerDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The amount of tokens this contract token manager is allowed
  /// to provide backing for.
  ///
  /// Since contract token managers cannot increase or decrease
  /// their issuance limit, this should equal the `issued_tokens`.
  public var issuanceLimit: CurrencyValue? = nil

  /// Output only. The amount of tokens this contract token manager is
  /// providing backing for (that is, its total liability).
  ///
  /// This equals to the sum of all balances held in contracts for its currency,
  /// plus its net position in the settlement matrix.
  public var issuedTokens: CurrencyValue? = nil

  /// Output only. The account ID of the previous contract token manager for this
  /// currency. This forms an audit trail that can be traversed to discover all
  /// previous managers. If this is the first contract token manager for the
  /// currency, this will be empty.
  public var previousContractTokenManagerId: Swift.String = Swift.String()

  /// Output only. The status of this account.
  public var accountStatus: AccountStatus = AccountStatus()

  /// Initialize a new instance of `ContractTokenManagerDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContractTokenManagerDetails().with { $0.issuanceLimit = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ContractTokenManagerDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
