// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Stores a contract on the ledger.
public struct CreateContract: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Serialised contract bytes.
  public var contractBytes: Foundation.Data = Foundation.Data()

  /// Optional. Immutable. Deprecated: Use
  /// [init_arguments][google.cloud.universalledger.v1.CreateContract.init_arguments]
  /// instead. Arguments for the `__init__` method.
  ///
  /// [google.cloud.universalledger.v1.CreateContract.init_arguments]: <doc:CreateContract/initArguments>
  @available(*, deprecated)
  public var arguments: [Swift.String: Value] = [:]

  /// Optional. Immutable. Contains arguments for the `__init__` method.
  public var initArguments: [Swift.String: Value] = [:]

  /// Optional. Immutable. An opaque comment field that is not interpreted by the
  /// system but stored on the ledger in the contract. Considered public
  /// information. Maximum length is 128 characters. May be left empty. Once
  /// created, the field is immutable.
  public var contractComment: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateContract`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateContract().with { $0.contractBytes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.CreateContract"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
