// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Stores a contract on the ledger.
public struct CreateContract: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Serialised contract bytes.
  public var contractBytes: Foundation.Data = Foundation.Data()

  /// Optional. Immutable. Deprecated: Use
  /// [init_arguments][google.cloud.universalledger.v1.CreateContract.init_arguments]
  /// instead. Arguments for the `__init__` method.
  ///
  /// [google.cloud.universalledger.v1.CreateContract.init_arguments]: <doc:CreateContract/initArguments>
  @available(*, deprecated)
  public var arguments: [Swift.String: Value] = [:]

  /// Optional. Immutable. Contains arguments for the `__init__` method.
  public var initArguments: [Swift.String: Value] = [:]

  /// Optional. Immutable. An opaque comment field that is not interpreted by the
  /// system but stored on the ledger in the contract. Considered public
  /// information. Maximum length is 128 characters. May be left empty. Once
  /// created, the field is immutable.
  public var contractComment: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateContract`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateContract().with { $0.contractBytes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let contractBytes = CodingKeys(stringValue: "contractBytes")
    static let arguments = CodingKeys(stringValue: "arguments")
    static let initArguments = CodingKeys(stringValue: "initArguments")
    static let contractComment = CodingKeys(stringValue: "contractComment")

    static let _knownKeys: Set<Swift.String> = [
      "contractBytes",
      "arguments",
      "initArguments",
      "contractComment",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .contractBytes) {
      self.contractBytes = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Value].self, forKey: .arguments) {
      self.arguments = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Value].self, forKey: .initArguments)
    {
      self.initArguments = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .contractComment) {
      self.contractComment = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.contractBytes, forKey: .contractBytes)
    try container.encode(self.arguments, forKey: .arguments)
    try container.encode(self.initArguments, forKey: .initArguments)
    try container.encode(self.contractComment, forKey: .contractComment)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.CreateContract"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
