// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents an amount of currency (i.e. money). Note that the denominated
/// currency is not included in this message. The relevant currency is decided by
/// the account that sends the transaction. Each account has a unique immutable
/// currency associated to it.
public struct CurrencyValue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The number of minor units of the currency.
  ///
  ///
  /// This smallest valid denomination is referred to as "minor units" and is
  /// specified in [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html).
  /// As an example, for USD, the value will be the number of cents and for GBP
  /// it will be the number of pence. For the Japanese Yen which does not have a
  /// minor unit, it will be the number of Yen.
  public var value: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `CurrencyValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CurrencyValue().with { $0.value = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.CurrencyValue"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
