// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details specific to a Currency Operator.
public struct CurrencyOperatorDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Deprecated: Use `currency_code` instead.
  /// The currency associated with this account, represented by the 3-letter
  /// ISO 4217 code.
  @available(*, deprecated)
  public var currency: Swift.String = Swift.String()

  /// Output only. The ID of the currency associated with this account,
  /// represented by the 3-letter ISO 4217 code.
  public var currencyCode: Swift.String = Swift.String()

  /// Output only. The status of this account.
  public var accountStatus: AccountStatus = AccountStatus()

  /// Output only. Deprecated: Use `previous_currency_operator_id` instead.
  /// The previous currency operator which transferred ownership of the currency
  /// operator role to this account. If this is the first currency operator for
  /// the currency, this will be empty.
  @available(*, deprecated)
  public var previousEntityId: Entity? = nil

  /// Output only. The ID of the previous currency operator which transferred
  /// ownership of the currency operator role to this account. If this is the
  /// first currency operator for the currency, this will be empty.
  public var previousCurrencyOperatorId: Swift.String = Swift.String()

  /// Output only. Deprecated: Use `platform_operator_id` instead.
  /// The platform operator which created this currency operator.
  @available(*, deprecated)
  public var platformOperatorEntityId: Entity? = nil

  /// Output only. The ID of the platform operator which created this currency
  /// operator.
  public var platformOperatorId: Swift.String = Swift.String()

  /// Output only. Deprecated: Use `contract_token_manager_id` instead.
  /// The contract token manager associated with this currency operator.
  @available(*, deprecated)
  public var contractTokenManager: Entity? = nil

  /// Output only. The ID of the contract token manager associated with this
  /// currency operator.
  public var contractTokenManagerId: Swift.String = Swift.String()

  /// Output only. The ID of the clearinghouse associated with this currency
  /// operator.
  public var clearinghouseId: Swift.String = Swift.String()

  /// Initialize a new instance of `CurrencyOperatorDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CurrencyOperatorDetails().with { $0.currency = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.CurrencyOperatorDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
