// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Notifies the network that the target account wishes to withdraw reserve funds
/// and decreases its token issuance limit. The sender must be a clearinghouse
/// account.
///
/// Note that this transaction must be successfully finalized *before* the
/// reserve funds can be withdrawn. This is necessary because it is possible for
/// the transaction to fail (for example, if the minted amount is already above
/// the requested reduced limit).
public struct DecreaseTokenIssuanceLimit: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [token_manager_id][google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit.token_manager_id]
  /// instead. The ID of the institutional account whose mint limit is to be
  /// lowered. This account must be a token manager for the transaction to be
  /// valid.
  ///
  /// [google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit.token_manager_id]: <doc:DecreaseTokenIssuanceLimit/tokenManagerId>
  @available(*, deprecated)
  public var tokenManager: Entity? = nil

  /// Optional. The ID of the institutional account whose mint limit is to be
  /// lowered. This account must be a token manager for the transaction to be
  /// valid. One of `token_manager_id` (preferred) or `token_manager`
  /// (deprecated) must be specified.
  public var tokenManagerId: Swift.String = Swift.String()

  /// Required. The amount by which to lower the limit. The amount must be
  /// positive. The transaction will fail if the reduced limit will fall below
  /// the currently issued tokens.
  public var amount: CurrencyValue? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DecreaseTokenIssuanceLimit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DecreaseTokenIssuanceLimit().with { $0.tokenManager = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tokenManager = CodingKeys(stringValue: "tokenManager")
    static let tokenManagerId = CodingKeys(stringValue: "tokenManagerId")
    static let amount = CodingKeys(stringValue: "amount")

    static let _knownKeys: Set<Swift.String> = [
      "tokenManager",
      "tokenManagerId",
      "amount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.tokenManager = try container.decodeIfPresent(Entity.self, forKey: .tokenManager)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tokenManagerId) {
      self.tokenManagerId = value
    }
    self.amount = try container.decodeIfPresent(CurrencyValue.self, forKey: .amount)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.tokenManager, forKey: .tokenManager)
    try container.encode(self.tokenManagerId, forKey: .tokenManagerId)
    try container.encodeIfPresent(self.amount, forKey: .amount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
