// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Notifies the network that the target account wishes to withdraw reserve funds
/// and decreases its token issuance limit. The sender must be a clearinghouse
/// account.
///
/// Note that this transaction must be successfully finalized *before* the
/// reserve funds can be withdrawn. This is necessary because it is possible for
/// the transaction to fail (for example, if the minted amount is already above
/// the requested reduced limit).
public struct DecreaseTokenIssuanceLimit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [token_manager_id][google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit.token_manager_id]
  /// instead. The ID of the institutional account whose mint limit is to be
  /// lowered. This account must be a token manager for the transaction to be
  /// valid.
  ///
  /// [google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit.token_manager_id]: <doc:DecreaseTokenIssuanceLimit/tokenManagerId>
  @available(*, deprecated)
  public var tokenManager: Entity? = nil

  /// Optional. The ID of the institutional account whose mint limit is to be
  /// lowered. This account must be a token manager for the transaction to be
  /// valid. One of `token_manager_id` (preferred) or `token_manager`
  /// (deprecated) must be specified.
  public var tokenManagerId: Swift.String = Swift.String()

  /// Required. The amount by which to lower the limit. The amount must be
  /// positive. The transaction will fail if the reduced limit will fall below
  /// the currently issued tokens.
  public var amount: CurrencyValue? = nil

  /// Initialize a new instance of `DecreaseTokenIssuanceLimit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DecreaseTokenIssuanceLimit().with { $0.tokenManager = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.DecreaseTokenIssuanceLimit"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
