// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Indices map key to value. For example, `keys[0]` key maps to `values[0]`.
public struct DictValue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Each key can be exactly one kind.
  public var keys: OneOf_Keys? = nil

  /// Each value can be exactly one kind.
  public var values: OneOf_Values? = nil

  /// Initialize a new instance of `DictValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DictValue().with { $0.boolKeys = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case boolKeys = "boolKeys"
    case stringKeys = "stringKeys"
    case int64Keys = "int64Keys"
    case accountIdKeys = "accountIdKeys"
    case boolValues = "boolValues"
    case stringValues = "stringValues"
    case int64Values = "int64Values"
    case dictValues = "dictValues"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var keys: OneOf_Keys? = nil
    let keysCheckAndSet = {
      if keys != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'keys'"
          ))
      }
      keys = $0
    }
    if let boolKeys = try container.decodeIfPresent(BoolList?.self, forKey: .boolKeys) {
      try keysCheckAndSet(.boolKeys(boolKeys))
    }
    if let stringKeys = try container.decodeIfPresent(StringList?.self, forKey: .stringKeys) {
      try keysCheckAndSet(.stringKeys(stringKeys))
    }
    if let int64Keys = try container.decodeIfPresent(Int64List?.self, forKey: .int64Keys) {
      try keysCheckAndSet(.int64Keys(int64Keys))
    }
    if let accountIdKeys = try container.decodeIfPresent(
      AccountIdList?.self, forKey: .accountIdKeys)
    {
      try keysCheckAndSet(.accountIdKeys(accountIdKeys))
    }
    self.keys = keys

    var values: OneOf_Values? = nil
    let valuesCheckAndSet = {
      if values != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'values'"))
      }
      values = $0
    }
    if let boolValues = try container.decodeIfPresent(BoolList?.self, forKey: .boolValues) {
      try valuesCheckAndSet(.boolValues(boolValues))
    }
    if let stringValues = try container.decodeIfPresent(StringList?.self, forKey: .stringValues) {
      try valuesCheckAndSet(.stringValues(stringValues))
    }
    if let int64Values = try container.decodeIfPresent(Int64List?.self, forKey: .int64Values) {
      try valuesCheckAndSet(.int64Values(int64Values))
    }
    if let dictValues = try container.decodeIfPresent(DictList?.self, forKey: .dictValues) {
      try valuesCheckAndSet(.dictValues(dictValues))
    }
    self.values = values
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.keys {
      switch choice {
      case .boolKeys(let value):
        try container.encode(value, forKey: .boolKeys)
      case .stringKeys(let value):
        try container.encode(value, forKey: .stringKeys)
      case .int64Keys(let value):
        try container.encode(value, forKey: .int64Keys)
      case .accountIdKeys(let value):
        try container.encode(value, forKey: .accountIdKeys)
      }
    }

    if let choice = self.values {
      switch choice {
      case .boolValues(let value):
        try container.encode(value, forKey: .boolValues)
      case .stringValues(let value):
        try container.encode(value, forKey: .stringValues)
      case .int64Values(let value):
        try container.encode(value, forKey: .int64Values)
      case .dictValues(let value):
        try container.encode(value, forKey: .dictValues)
      }
    }
  }

  /// Each key can be exactly one kind.
  public enum OneOf_Keys: Codable, Equatable, Sendable {
    /// Optional. A list of boolean keys.
    indirect case boolKeys(BoolList?)
    /// Optional. A list of string keys.
    indirect case stringKeys(StringList?)
    /// Optional. A list of int64 keys.
    indirect case int64Keys(Int64List?)
    /// Optional. A list of account ID keys.
    indirect case accountIdKeys(AccountIdList?)
  }

  /// Each value can be exactly one kind.
  public enum OneOf_Values: Codable, Equatable, Sendable {
    /// Optional. A list of boolean values.
    indirect case boolValues(BoolList?)
    /// Optional. A list of string values.
    indirect case stringValues(StringList?)
    /// Optional. A list of int64 values.
    indirect case int64Values(Int64List?)
    /// Optional. Values are a list of nested dictionaries.
    indirect case dictValues(DictList?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.DictValue"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
