// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Indices map key to value. For example, `keys[0]` key maps to `values[0]`.
public struct DictValue: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Each key can be exactly one kind.
  public var keys: KeysOneOf? = nil

  /// Each value can be exactly one kind.
  public var values: ValuesOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DictValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DictValue().with { $0.boolKeys = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let boolKeys = CodingKeys(stringValue: "boolKeys")
    static let stringKeys = CodingKeys(stringValue: "stringKeys")
    static let int64Keys = CodingKeys(stringValue: "int64Keys")
    static let genericKeys = CodingKeys(stringValue: "genericKeys")
    static let boolValues = CodingKeys(stringValue: "boolValues")
    static let stringValues = CodingKeys(stringValue: "stringValues")
    static let int64Values = CodingKeys(stringValue: "int64Values")
    static let genericValues = CodingKeys(stringValue: "genericValues")

    static let _knownKeys: Set<Swift.String> = [
      "boolKeys",
      "stringKeys",
      "int64Keys",
      "genericKeys",
      "boolValues",
      "stringValues",
      "int64Values",
      "genericValues",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var keys: KeysOneOf? = nil
    let keysCheckAndSet = {
      if keys != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'keys'"
          ))
      }
      keys = $0
    }
    if let boolKeys = try container.decodeIfPresent(BoolList.self, forKey: .boolKeys) {
      try keysCheckAndSet(.boolKeys(boolKeys))
    }
    if let stringKeys = try container.decodeIfPresent(StringList.self, forKey: .stringKeys) {
      try keysCheckAndSet(.stringKeys(stringKeys))
    }
    if let int64Keys = try container.decodeIfPresent(Int64List.self, forKey: .int64Keys) {
      try keysCheckAndSet(.int64Keys(int64Keys))
    }
    if let genericKeys = try container.decodeIfPresent(RepeatedValue.self, forKey: .genericKeys) {
      try keysCheckAndSet(.genericKeys(genericKeys))
    }
    self.keys = keys

    var values: ValuesOneOf? = nil
    let valuesCheckAndSet = {
      if values != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'values'"))
      }
      values = $0
    }
    if let boolValues = try container.decodeIfPresent(BoolList.self, forKey: .boolValues) {
      try valuesCheckAndSet(.boolValues(boolValues))
    }
    if let stringValues = try container.decodeIfPresent(StringList.self, forKey: .stringValues) {
      try valuesCheckAndSet(.stringValues(stringValues))
    }
    if let int64Values = try container.decodeIfPresent(Int64List.self, forKey: .int64Values) {
      try valuesCheckAndSet(.int64Values(int64Values))
    }
    if let genericValues = try container.decodeIfPresent(RepeatedValue.self, forKey: .genericValues)
    {
      try valuesCheckAndSet(.genericValues(genericValues))
    }
    self.values = values
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.keys {
      switch choice {
      case .boolKeys(let value):
        try container.encode(value, forKey: .boolKeys)
      case .stringKeys(let value):
        try container.encode(value, forKey: .stringKeys)
      case .int64Keys(let value):
        try container.encode(value, forKey: .int64Keys)
      case .genericKeys(let value):
        try container.encode(value, forKey: .genericKeys)
      }
    }

    if let choice = self.values {
      switch choice {
      case .boolValues(let value):
        try container.encode(value, forKey: .boolValues)
      case .stringValues(let value):
        try container.encode(value, forKey: .stringValues)
      case .int64Values(let value):
        try container.encode(value, forKey: .int64Values)
      case .genericValues(let value):
        try container.encode(value, forKey: .genericValues)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Each key can be exactly one kind.
  public enum KeysOneOf: Codable, Equatable, Sendable {
    /// Optional. A list of boolean keys.
    indirect case boolKeys(BoolList)
    /// Optional. A list of string keys.
    indirect case stringKeys(StringList)
    /// Optional. A list of int64 keys.
    indirect case int64Keys(Int64List)
    /// Optional. A generic list of keys.
    indirect case genericKeys(RepeatedValue)
  }

  /// Each value can be exactly one kind.
  public enum ValuesOneOf: Codable, Equatable, Sendable {
    /// Optional. A list of boolean values.
    indirect case boolValues(BoolList)
    /// Optional. A list of string values.
    indirect case stringValues(StringList)
    /// Optional. A list of int64 values.
    indirect case int64Values(Int64List)
    /// Optional. A generic list of values as values.
    indirect case genericValues(RepeatedValue)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.DictValue"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
