// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Represents the type of an event in the processing of a transaction, as
/// observed by the validator that the request was routed to.
public enum EventType: Codable, Equatable, Sendable {
  /// Unknown or unspecified event.
  case unspecified
  /// The transaction was received by this validator directly from a client.
  case received
  /// The transaction was broadcasted by this to other validators.
  case broadcasted
  /// The transaction was ordered and scheduled for execution by this validator.
  case ordered
  /// The execution of the transaction has started.
  case executionStarted
  /// The execution of the transaction has completed.
  case executionCompleted
  /// The transaction has been finalized by this validator.
  case finalized
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .received: return 1
    case .broadcasted: return 2
    case .ordered: return 3
    case .executionStarted: return 4
    case .executionCompleted: return 5
    case .finalized: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
    case .received: return "EVENT_TYPE_RECEIVED"
    case .broadcasted: return "EVENT_TYPE_BROADCASTED"
    case .ordered: return "EVENT_TYPE_ORDERED"
    case .executionStarted: return "EVENT_TYPE_EXECUTION_STARTED"
    case .executionCompleted: return "EVENT_TYPE_EXECUTION_COMPLETED"
    case .finalized: return "EVENT_TYPE_FINALIZED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
    case "EVENT_TYPE_RECEIVED": self = .received
    case "EVENT_TYPE_BROADCASTED": self = .broadcasted
    case "EVENT_TYPE_ORDERED": self = .ordered
    case "EVENT_TYPE_EXECUTION_STARTED": self = .executionStarted
    case "EVENT_TYPE_EXECUTION_COMPLETED": self = .executionCompleted
    case "EVENT_TYPE_FINALIZED": self = .finalized
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .received
    case 2: self = .broadcasted
    case 3: self = .ordered
    case 4: self = .executionStarted
    case 5: self = .executionCompleted
    case 6: self = .finalized
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .received: return try container.encode(1)
    case .broadcasted: return try container.encode(2)
    case .ordered: return try container.encode(3)
    case .executionStarted: return try container.encode(4)
    case .executionCompleted: return try container.encode(5)
    case .finalized: return try container.encode(6)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
