// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents additional details of a status event.
public struct EventDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The details of the event.
  public var eventDetails: OneOf_EventDetails? = nil

  /// Initialize a new instance of `EventDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventDetails().with { $0.executionDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case executionDetails = "executionDetails"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var eventDetails: OneOf_EventDetails? = nil
    let eventDetailsCheckAndSet = {
      if eventDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'eventDetails'"))
      }
      eventDetails = $0
    }
    if let executionDetails = try container.decodeIfPresent(
      ExecutionDetails?.self, forKey: .executionDetails)
    {
      try eventDetailsCheckAndSet(.executionDetails(executionDetails))
    }
    self.eventDetails = eventDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.eventDetails {
      switch choice {
      case .executionDetails(let value):
        try container.encode(value, forKey: .executionDetails)
      }
    }
  }

  /// The details of the event.
  public enum OneOf_EventDetails: Codable, Equatable, Sendable {
    /// Output only. Additional details for an execution event.
    indirect case executionDetails(ExecutionDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.EventDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
