// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Grants permissions to the contract by the transaction sender.
/// If `delegate_contract_id` is specified, the permissions and corresponding
/// storage are granted exclusively to the `delegate_contract_id` contract, not
/// the sender.
///
/// Note that there is no support for revoking permissions.
public struct GrantContractPermissions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [contract_id][google.cloud.universalledger.v1.GrantContractPermissions.contract_id]
  /// instead. ID of the contract to which permissions are being granted.
  ///
  /// [google.cloud.universalledger.v1.GrantContractPermissions.contract_id]: <doc:GrantContractPermissions/contractId>
  @available(*, deprecated)
  public var contract: Entity? = nil

  /// Optional. The ID of the contract to which permissions are being granted.
  /// One of `contract` or `contract_id` must be specified.
  public var contractId: Swift.String = Swift.String()

  /// The permissions to be granted.
  public var permissions: [ContractPermission] = []

  /// Optional. The contract ID for which permissions are being granted.
  /// The transaction sender must be the owner of this contract.
  public var delegateContractId: Swift.String = Swift.String()

  /// Initialize a new instance of `GrantContractPermissions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GrantContractPermissions().with { $0.contract = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.GrantContractPermissions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
