// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Transactions for token issuance and minting.
/// Notifies the network that the target account has deposited reserve funds and
/// increases its token issuance limit. The sender must be a clearinghouse
/// account.
public struct IncreaseTokenIssuanceLimit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [token_manager_id][google.cloud.universalledger.v1.IncreaseTokenIssuanceLimit.token_manager_id]
  /// instead. The ID of the institutional account whose mint limit is to be
  /// raised. This account must be a token manager for the transaction to be
  /// valid.
  ///
  /// [google.cloud.universalledger.v1.IncreaseTokenIssuanceLimit.token_manager_id]: <doc:IncreaseTokenIssuanceLimit/tokenManagerId>
  @available(*, deprecated)
  public var tokenManager: Entity? = nil

  /// Optional. The ID of the institutional account whose mint limit is to be
  /// raised. This account must be a token manager for the transaction to be
  /// valid. One of `token_manager` or `token_manager_id` must be specified.
  public var tokenManagerId: Swift.String = Swift.String()

  /// Required. The amount by which to raise the limit. The amount must be
  /// positive.
  public var amount: CurrencyValue? = nil

  /// Initialize a new instance of `IncreaseTokenIssuanceLimit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IncreaseTokenIssuanceLimit().with { $0.tokenManager = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.IncreaseTokenIssuanceLimit"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
