// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Invokes the execution of a contract method.
public struct InvokeContractMethod: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [contract_id][google.cloud.universalledger.v1.InvokeContractMethod.contract_id]
  /// instead. ID of the contract to run.
  ///
  /// [google.cloud.universalledger.v1.InvokeContractMethod.contract_id]: <doc:InvokeContractMethod/contractId>
  @available(*, deprecated)
  public var contract: Entity? = nil

  /// Optional. The ID of the contract to run. One of `contract` or `contract_id`
  /// must be specified.
  public var contractId: Swift.String = Swift.String()

  /// Name of the method to run.
  public var methodName: Swift.String = Swift.String()

  /// Optional. Immutable. Deprecated: Use
  /// [method_arguments][google.cloud.universalledger.v1.InvokeContractMethod.method_arguments]
  /// instead. Arguments for the method.
  ///
  /// [google.cloud.universalledger.v1.InvokeContractMethod.method_arguments]: <doc:InvokeContractMethod/methodArguments>
  @available(*, deprecated)
  public var arguments: [Swift.String: Value] = [:]

  /// Optional. Immutable. Contains arguments to pass to the method.
  public var methodArguments: [Swift.String: Value] = [:]

  /// The amount to be paid.
  /// Must be greater than zero when invoking payable methods; and zero for
  /// non-payable ones.
  public var payment: CurrencyValue? = nil

  /// Initialize a new instance of `InvokeContractMethod`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InvokeContractMethod().with { $0.contract = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.InvokeContractMethod"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
