// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Invokes the execution of a contract method.
public struct InvokeContractMethod: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [contract_id][google.cloud.universalledger.v1.InvokeContractMethod.contract_id]
  /// instead. ID of the contract to run.
  ///
  /// [google.cloud.universalledger.v1.InvokeContractMethod.contract_id]: <doc:InvokeContractMethod/contractId>
  @available(*, deprecated)
  public var contract: Entity? = nil

  /// Optional. The ID of the contract to run. One of `contract` or `contract_id`
  /// must be specified.
  public var contractId: Swift.String = Swift.String()

  /// Name of the method to run.
  public var methodName: Swift.String = Swift.String()

  /// Optional. Immutable. Deprecated: Use
  /// [method_arguments][google.cloud.universalledger.v1.InvokeContractMethod.method_arguments]
  /// instead. Arguments for the method.
  ///
  /// [google.cloud.universalledger.v1.InvokeContractMethod.method_arguments]: <doc:InvokeContractMethod/methodArguments>
  @available(*, deprecated)
  public var arguments: [Swift.String: Value] = [:]

  /// Optional. Immutable. Contains arguments to pass to the method.
  public var methodArguments: [Swift.String: Value] = [:]

  /// The amount to be paid.
  /// Must be greater than zero when invoking payable methods; and zero for
  /// non-payable ones.
  public var payment: CurrencyValue? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InvokeContractMethod`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InvokeContractMethod().with { $0.contract = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let contract = CodingKeys(stringValue: "contract")
    static let contractId = CodingKeys(stringValue: "contractId")
    static let methodName = CodingKeys(stringValue: "methodName")
    static let arguments = CodingKeys(stringValue: "arguments")
    static let methodArguments = CodingKeys(stringValue: "methodArguments")
    static let payment = CodingKeys(stringValue: "payment")

    static let _knownKeys: Set<Swift.String> = [
      "contract",
      "contractId",
      "methodName",
      "arguments",
      "methodArguments",
      "payment",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.contract = try container.decodeIfPresent(Entity.self, forKey: .contract)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .contractId) {
      self.contractId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .methodName) {
      self.methodName = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Value].self, forKey: .arguments) {
      self.arguments = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Value].self, forKey: .methodArguments)
    {
      self.methodArguments = value
    }
    self.payment = try container.decodeIfPresent(CurrencyValue.self, forKey: .payment)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.contract, forKey: .contract)
    try container.encode(self.contractId, forKey: .contractId)
    try container.encode(self.methodName, forKey: .methodName)
    try container.encode(self.arguments, forKey: .arguments)
    try container.encode(self.methodArguments, forKey: .methodArguments)
    try container.encodeIfPresent(self.payment, forKey: .payment)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.InvokeContractMethod"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
