// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A list of values.
public struct ListValue: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Each value can be exactly one kind.
  public var values: ValuesOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListValue().with { $0.boolValues = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let boolValues = CodingKeys(stringValue: "boolValues")
    static let stringValues = CodingKeys(stringValue: "stringValues")
    static let int64Values = CodingKeys(stringValue: "int64Values")
    static let genericValues = CodingKeys(stringValue: "genericValues")

    static let _knownKeys: Set<Swift.String> = [
      "boolValues",
      "stringValues",
      "int64Values",
      "genericValues",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var values: ValuesOneOf? = nil
    let valuesCheckAndSet = {
      if values != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'values'"))
      }
      values = $0
    }
    if let boolValues = try container.decodeIfPresent(BoolList.self, forKey: .boolValues) {
      try valuesCheckAndSet(.boolValues(boolValues))
    }
    if let stringValues = try container.decodeIfPresent(StringList.self, forKey: .stringValues) {
      try valuesCheckAndSet(.stringValues(stringValues))
    }
    if let int64Values = try container.decodeIfPresent(Int64List.self, forKey: .int64Values) {
      try valuesCheckAndSet(.int64Values(int64Values))
    }
    if let genericValues = try container.decodeIfPresent(RepeatedValue.self, forKey: .genericValues)
    {
      try valuesCheckAndSet(.genericValues(genericValues))
    }
    self.values = values
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.values {
      switch choice {
      case .boolValues(let value):
        try container.encode(value, forKey: .boolValues)
      case .stringValues(let value):
        try container.encode(value, forKey: .stringValues)
      case .int64Values(let value):
        try container.encode(value, forKey: .int64Values)
      case .genericValues(let value):
        try container.encode(value, forKey: .genericValues)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Each value can be exactly one kind.
  public enum ValuesOneOf: Codable, Equatable, Sendable {
    /// Optional. A list of boolean values.
    indirect case boolValues(BoolList)
    /// Optional. A list of string values.
    indirect case stringValues(StringList)
    /// Optional. A list of int64 values.
    indirect case int64Values(Int64List)
    /// Optional. A generic list of values.
    indirect case genericValues(RepeatedValue)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ListValue"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
