// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Merkle tree with a cryptographic digest of the root node.
public struct MerkleTree: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The cryptographic digest of the root node.
  /// Deprecated: Use
  /// [root_digest_hex][google.cloud.universalledger.v1.MerkleTree.root_digest_hex]
  /// instead.
  ///
  /// [google.cloud.universalledger.v1.MerkleTree.root_digest_hex]: <doc:MerkleTree/rootDigestHex>
  @available(*, deprecated)
  public var rootHashHex: Swift.String = Swift.String()

  /// Output only. The hexadecimal representation of the digest of the root node.
  /// Format: A 64-character hexadecimal string.
  public var rootDigestHex: Swift.String = Swift.String()

  /// Output only. The number of transactions in the tree.
  public var numTransactions: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `MerkleTree`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MerkleTree().with { $0.rootHashHex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.MerkleTree"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
