// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Mints currency tokens and transfers them to a specified account. The sender
/// must be a token manager.
public struct Mint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The amount to mint. The amount must be such that the total tokens
  /// minted by the token manager do not exceed the mint limit. If the amount is
  /// higher than that, the transaction must be rejected
  public var mintAmount: CurrencyValue? = nil

  /// Optional. Deprecated: Use
  /// [beneficiary_id][google.cloud.universalledger.v1.Mint.beneficiary_id]
  /// instead. The account to which the minted amount should be transferred. The
  /// beneficiary account must have the `ROLE_RECEIVER` enabled on it.
  ///
  /// [google.cloud.universalledger.v1.Mint.beneficiary_id]: <doc:Mint/beneficiaryId>
  @available(*, deprecated)
  public var beneficiary: Entity? = nil

  /// Optional. The ID of the account to which the minted amount should be
  /// transferred. The receiving account must have the `ROLE_RECEIVER` enabled on
  /// it. One of `beneficiary` or `beneficiary_id` must be specified.
  public var beneficiaryId: Swift.String = Swift.String()

  /// Initialize a new instance of `Mint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Mint().with { $0.mintAmount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.Mint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
