// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Mints currency tokens and transfers them to a specified account. The sender
/// must be a token manager.
public struct Mint: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The amount to mint. The amount must be such that the total tokens
  /// minted by the token manager do not exceed the mint limit. If the amount is
  /// higher than that, the transaction must be rejected
  public var mintAmount: CurrencyValue? = nil

  /// Optional. Deprecated: Use
  /// [beneficiary_id][google.cloud.universalledger.v1.Mint.beneficiary_id]
  /// instead. The account to which the minted amount should be transferred. The
  /// beneficiary account must have the `ROLE_RECEIVER` enabled on it.
  ///
  /// [google.cloud.universalledger.v1.Mint.beneficiary_id]: <doc:Mint/beneficiaryId>
  @available(*, deprecated)
  public var beneficiary: Entity? = nil

  /// Optional. The ID of the account to which the minted amount should be
  /// transferred. The receiving account must have the `ROLE_RECEIVER` enabled on
  /// it. One of `beneficiary` or `beneficiary_id` must be specified.
  public var beneficiaryId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Mint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Mint().with { $0.mintAmount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let mintAmount = CodingKeys(stringValue: "mintAmount")
    static let beneficiary = CodingKeys(stringValue: "beneficiary")
    static let beneficiaryId = CodingKeys(stringValue: "beneficiaryId")

    static let _knownKeys: Set<Swift.String> = [
      "mintAmount",
      "beneficiary",
      "beneficiaryId",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.mintAmount = try container.decodeIfPresent(CurrencyValue.self, forKey: .mintAmount)
    self.beneficiary = try container.decodeIfPresent(Entity.self, forKey: .beneficiary)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .beneficiaryId) {
      self.beneficiaryId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.mintAmount, forKey: .mintAmount)
    try container.encodeIfPresent(self.beneficiary, forKey: .beneficiary)
    try container.encode(self.beneficiaryId, forKey: .beneficiaryId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.Mint"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
