// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Certificate of the inclusion of the effects of a transaction in the world
/// state.
public struct ProofOfInclusion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Certificate of the inclusion of the transaction effects in a
  /// specific round.
  public var transactionCertificate: TransactionCertificate? = nil

  /// Output only. Certificate of the execution of the round.
  public var roundCertificate: RoundCertificate? = nil

  /// Output only. Cryptographic proof of inclusion of the transaction effects in
  /// the execution round.
  ///
  /// It is given as a path from a given leaf (a transaction digest) to the root
  /// of the execution round. The path is represented as a list of (left child,
  /// right child) pairs, and the first pair is the left and right children of
  /// the given leaf's parent node. For example, assuming the Merkle tree was
  /// built with eight leaf digests `[t0, t1, t2, t3, t4, t5, t6, t7]`, having
  /// the following structure:
  ///
  ///            _____root_digest____
  ///           |                    |
  ///        __ h20__             __h21__
  ///       |        |           |       |
  ///      h10     h11          h12     h13
  ///      | |     | |          | |     | |
  ///     t0 t1   t2 t3        t4 t5   t6 t7
  ///
  /// In here, `path_to_round_root` for `t0` will contain:
  /// `[(t0, t1), (h10, h11), (h20, h21)]`.
  ///
  /// One can consecutively compute SHA-256 digests of each
  /// path node to verify that the digest of the path produces the same value as
  /// the `round_certificate.merkle_tree.root_digest_hex`. Thus, verifying that
  /// the leaf was included in the round's Merkle tree.
  public var pathToRoundRoot: [ProofOfInclusion.MerkleTreeNode] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProofOfInclusion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProofOfInclusion().with { $0.transactionCertificate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let transactionCertificate = CodingKeys(stringValue: "transactionCertificate")
    static let roundCertificate = CodingKeys(stringValue: "roundCertificate")
    static let pathToRoundRoot = CodingKeys(stringValue: "pathToRoundRoot")

    static let _knownKeys: Set<Swift.String> = [
      "transactionCertificate",
      "roundCertificate",
      "pathToRoundRoot",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.transactionCertificate = try container.decodeIfPresent(
      TransactionCertificate.self, forKey: .transactionCertificate)
    self.roundCertificate = try container.decodeIfPresent(
      RoundCertificate.self, forKey: .roundCertificate)
    if let value = try container.decodeIfPresent(
      [ProofOfInclusion.MerkleTreeNode].self, forKey: .pathToRoundRoot)
    {
      self.pathToRoundRoot = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.transactionCertificate, forKey: .transactionCertificate)
    try container.encodeIfPresent(self.roundCertificate, forKey: .roundCertificate)
    try container.encode(self.pathToRoundRoot, forKey: .pathToRoundRoot)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents a node in a Merkle tree path.
  public struct MerkleTreeNode: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The hexadecimal representation of the digest of the left
    /// child of a node. Deprecated: Use
    /// [left_child_digest_hex][google.cloud.universalledger.v1.ProofOfInclusion.MerkleTreeNode.left_child_digest_hex]
    /// instead.
    ///
    /// [google.cloud.universalledger.v1.ProofOfInclusion.MerkleTreeNode.left_child_digest_hex]: <doc:ProofOfInclusion/MerkleTreeNode/leftChildDigestHex>
    @available(*, deprecated)
    public var leftChildHashHex: Swift.String = Swift.String()

    /// Output only. The hexadecimal representation of the digest of the right
    /// child of a node. Deprecated: Use
    /// [right_child_digest_hex][google.cloud.universalledger.v1.ProofOfInclusion.MerkleTreeNode.right_child_digest_hex]
    /// instead.
    ///
    /// [google.cloud.universalledger.v1.ProofOfInclusion.MerkleTreeNode.right_child_digest_hex]: <doc:ProofOfInclusion/MerkleTreeNode/rightChildDigestHex>
    @available(*, deprecated)
    public var rightChildHashHex: Swift.String = Swift.String()

    /// Output only. The hexadecimal representation of the digest of the left
    /// child of a node. Format: A 64-character hexadecimal string.
    public var leftChildDigestHex: Swift.String = Swift.String()

    /// Output only. The hexadecimal representation of the digest of the right
    /// child of a node. Format: A 64-character hexadecimal string.
    public var rightChildDigestHex: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MerkleTreeNode`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MerkleTreeNode().with { $0.leftChildHashHex = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let leftChildHashHex = CodingKeys(stringValue: "leftChildHashHex")
      static let rightChildHashHex = CodingKeys(stringValue: "rightChildHashHex")
      static let leftChildDigestHex = CodingKeys(stringValue: "leftChildDigestHex")
      static let rightChildDigestHex = CodingKeys(stringValue: "rightChildDigestHex")

      static let _knownKeys: Set<Swift.String> = [
        "leftChildHashHex",
        "rightChildHashHex",
        "leftChildDigestHex",
        "rightChildDigestHex",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .leftChildHashHex) {
        self.leftChildHashHex = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rightChildHashHex) {
        self.rightChildHashHex = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .leftChildDigestHex) {
        self.leftChildDigestHex = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rightChildDigestHex)
      {
        self.rightChildDigestHex = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.leftChildHashHex, forKey: .leftChildHashHex)
      try container.encode(self.rightChildHashHex, forKey: .rightChildHashHex)
      try container.encode(self.leftChildDigestHex, forKey: .leftChildDigestHex)
      try container.encode(self.rightChildDigestHex, forKey: .rightChildDigestHex)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.universalledger.v1.ProofOfInclusion.MerkleTreeNode"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ProofOfInclusion"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
