// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response message for QueryData.
public struct QueryDataResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Indicates which fields have been redacted from the response due to
  /// permission restrictions.
  public var redactedFields: [RedactedField] = []

  /// The query-specific result.
  public var kind: OneOf_Kind? = nil

  /// Initialize a new instance of `QueryDataResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryDataResponse().with { $0.account = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case account = "account"
    case transactionState = "transactionState"
    case redactedFields = "redactedFields"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.redactedFields = try container.decode([RedactedField].self, forKey: .redactedFields)

    var kind: OneOf_Kind? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let account = try container.decodeIfPresent(Account?.self, forKey: .account) {
      try kindCheckAndSet(.account(account))
    }
    if let transactionState = try container.decodeIfPresent(
      TransactionState?.self, forKey: .transactionState)
    {
      try kindCheckAndSet(.transactionState(transactionState))
    }
    self.kind = kind
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.redactedFields, forKey: .redactedFields)

    if let choice = self.kind {
      switch choice {
      case .account(let value):
        try container.encode(value, forKey: .account)
      case .transactionState(let value):
        try container.encode(value, forKey: .transactionState)
      }
    }
  }

  /// The query-specific result.
  public enum OneOf_Kind: Codable, Equatable, Sendable {
    /// The account information, if the query was for an account.
    indirect case account(Account?)
    /// The state of a transaction, if the query was for a transaction.
    indirect case transactionState(TransactionState?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.QueryDataResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
