// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for QueryAccount.
public struct QueryAccountRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The endpoint to serve the request.
  /// Format: `projects/{project}/locations/{location}/endpoints/{endpoint}`
  /// The location is a region.
  public var endpoint: Swift.String = Swift.String()

  /// Required. The account ID to get information about. The value is limited to
  /// 60 characters.
  public var accountId: Swift.String = Swift.String()

  /// Optional. The ID of the execution round (similar to block "height") at
  /// which to request data. The returned account information will be accurate
  /// for the world state at this execution round. If unspecified, uses the
  /// latest finalized round as known by the serving validator. The state at a
  /// given round ID is always consistent and canonical.
  public var roundId: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `QueryAccountRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryAccountRequest().with { $0.endpoint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.QueryAccountRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
