// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about a redacted field in the response.
public struct RedactedField: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The fully qualified field paths that were redacted from the
  /// payload.
  public var redactedPath: GoogleWKT.WKTFieldMask? = nil

  /// Output only. A human-readable explanation of why the fields were redacted.
  public var reason: Swift.String = Swift.String()

  /// Output only. A machine readable code for why the fields were redacted.
  public var reasonCode: GoogleRpc.Code = GoogleRpc.Code()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RedactedField`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RedactedField().with { $0.redactedPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let redactedPath = CodingKeys(stringValue: "redactedPath")
    static let reason = CodingKeys(stringValue: "reason")
    static let reasonCode = CodingKeys(stringValue: "reasonCode")

    static let _knownKeys: Set<Swift.String> = [
      "redactedPath",
      "reason",
      "reasonCode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.redactedPath = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .redactedPath)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reason) {
      self.reason = value
    }
    if let value = try container.decodeIfPresent(GoogleRpc.Code.self, forKey: .reasonCode) {
      self.reasonCode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.redactedPath, forKey: .redactedPath)
    try container.encode(self.reason, forKey: .reason)
    try container.encode(self.reasonCode, forKey: .reasonCode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.RedactedField"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
