// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Replaces the account signing key in the specified slot. The other slot must
/// not be empty, and must hold the key used to sign the `ClientTransaction`.
public struct ReplaceSigningPublicKey: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The key slot we're replacing the key in.
  public var keySlot: KeySlot = KeySlot()

  /// Required. The new public key, which will replace the public key in the
  /// specified slot.
  ///
  /// The format of the public key is defined by the new_key_format field.
  /// Considered public information.
  public var newPublicKey: Foundation.Data = Foundation.Data()

  /// Required. The key format of the new public key. See the definition of
  /// KeyFormat for a list of supported formats. Considered public information.
  public var newKeyFormat: KeyFormat = KeyFormat()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReplaceSigningPublicKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplaceSigningPublicKey().with { $0.keySlot = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let keySlot = CodingKeys(stringValue: "keySlot")
    static let newPublicKey = CodingKeys(stringValue: "newPublicKey")
    static let newKeyFormat = CodingKeys(stringValue: "newKeyFormat")

    static let _knownKeys: Set<Swift.String> = [
      "keySlot",
      "newPublicKey",
      "newKeyFormat",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(KeySlot.self, forKey: .keySlot) {
      self.keySlot = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .newPublicKey) {
      self.newPublicKey = value
    }
    if let value = try container.decodeIfPresent(KeyFormat.self, forKey: .newKeyFormat) {
      self.newKeyFormat = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.keySlot, forKey: .keySlot)
    try container.encode(self.newPublicKey, forKey: .newPublicKey)
    try container.encode(self.newKeyFormat, forKey: .newKeyFormat)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.ReplaceSigningPublicKey"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
