// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Initiates a settlement operation between two token managers.
/// The sender must be a clearinghouse account.
///
/// In the deferred
/// [SettlementMode][google.cloud.universalledger.v1.SettlementMode] where the
/// clearinghouse has custody of the token manager funds, this is the only
/// transaction that needs to be sent to execute a settlement between the two
/// token managers.
///
/// [google.cloud.universalledger.v1.SettlementMode]: <doc:SettlementMode>
public struct SettlementRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Immutable. Deprecated: Use
  /// [payer_id][google.cloud.universalledger.v1.SettlementRequest.payer_id]
  /// instead. The account ID of the party that needs to make the fund transfer.
  ///
  /// [google.cloud.universalledger.v1.SettlementRequest.payer_id]: <doc:SettlementRequest/payerId>
  @available(*, deprecated)
  public var payer: Entity? = nil

  /// Optional. Immutable. The account ID of the party that needs to make the
  /// fund transfer. One of `payer` or `payer_id` must be specified.
  public var payerId: Swift.String = Swift.String()

  /// Optional. Immutable. Deprecated: Use
  /// [beneficiary_id][google.cloud.universalledger.v1.SettlementRequest.beneficiary_id]
  /// instead. The account ID of the party that needs to be paid.
  ///
  /// [google.cloud.universalledger.v1.SettlementRequest.beneficiary_id]: <doc:SettlementRequest/beneficiaryId>
  @available(*, deprecated)
  public var beneficiary: Entity? = nil

  /// Optional. Immutable. The account ID of the party that will receive the
  /// funds. One of `beneficiary` or `beneficiary_id` must be specified.
  public var beneficiaryId: Swift.String = Swift.String()

  /// Required. Immutable. The balance of issued tokens that need to be
  /// transferred by the `payer` account to the `beneficiary` account on the
  /// ledger.
  public var balance: CurrencyValue? = nil

  /// Required. Immutable. The round ID at which this settlement amount was
  /// computed.
  public var roundId: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `SettlementRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SettlementRequest().with { $0.payer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.SettlementRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
