// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Initiates a settlement operation between two token managers.
/// The sender must be a clearinghouse account.
///
/// In the deferred
/// [SettlementMode][google.cloud.universalledger.v1.SettlementMode] where the
/// clearinghouse has custody of the token manager funds, this is the only
/// transaction that needs to be sent to execute a settlement between the two
/// token managers.
///
/// [google.cloud.universalledger.v1.SettlementMode]: <doc:SettlementMode>
public struct SettlementRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Immutable. Deprecated: Use
  /// [payer_id][google.cloud.universalledger.v1.SettlementRequest.payer_id]
  /// instead. The account ID of the party that needs to make the fund transfer.
  ///
  /// [google.cloud.universalledger.v1.SettlementRequest.payer_id]: <doc:SettlementRequest/payerId>
  @available(*, deprecated)
  public var payer: Entity? = nil

  /// Optional. Immutable. The account ID of the party that needs to make the
  /// fund transfer. One of `payer` or `payer_id` must be specified.
  public var payerId: Swift.String = Swift.String()

  /// Optional. Immutable. Deprecated: Use
  /// [beneficiary_id][google.cloud.universalledger.v1.SettlementRequest.beneficiary_id]
  /// instead. The account ID of the party that needs to be paid.
  ///
  /// [google.cloud.universalledger.v1.SettlementRequest.beneficiary_id]: <doc:SettlementRequest/beneficiaryId>
  @available(*, deprecated)
  public var beneficiary: Entity? = nil

  /// Optional. Immutable. The account ID of the party that will receive the
  /// funds. One of `beneficiary` or `beneficiary_id` must be specified.
  public var beneficiaryId: Swift.String = Swift.String()

  /// Required. Immutable. The balance of issued tokens that need to be
  /// transferred by the `payer` account to the `beneficiary` account on the
  /// ledger.
  public var balance: CurrencyValue? = nil

  /// Required. Immutable. The round ID at which this settlement amount was
  /// computed.
  public var roundId: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SettlementRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SettlementRequest().with { $0.payer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let payer = CodingKeys(stringValue: "payer")
    static let payerId = CodingKeys(stringValue: "payerId")
    static let beneficiary = CodingKeys(stringValue: "beneficiary")
    static let beneficiaryId = CodingKeys(stringValue: "beneficiaryId")
    static let balance = CodingKeys(stringValue: "balance")
    static let roundId = CodingKeys(stringValue: "roundId")

    static let _knownKeys: Set<Swift.String> = [
      "payer",
      "payerId",
      "beneficiary",
      "beneficiaryId",
      "balance",
      "roundId",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.payer = try container.decodeIfPresent(Entity.self, forKey: .payer)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .payerId) {
      self.payerId = value
    }
    self.beneficiary = try container.decodeIfPresent(Entity.self, forKey: .beneficiary)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .beneficiaryId) {
      self.beneficiaryId = value
    }
    self.balance = try container.decodeIfPresent(CurrencyValue.self, forKey: .balance)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .roundId) {
      self.roundId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.payer, forKey: .payer)
    try container.encode(self.payerId, forKey: .payerId)
    try container.encodeIfPresent(self.beneficiary, forKey: .beneficiary)
    try container.encode(self.beneficiaryId, forKey: .beneficiaryId)
    try container.encodeIfPresent(self.balance, forKey: .balance)
    try container.encode(self.roundId, forKey: .roundId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.SettlementRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
