// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A transaction with attached signatures. To submit a transaction, this message
/// should be serialized and included in a
/// [SubmitTransactionRequest][google.cloud.universalledger.v1.SubmitTransactionRequest].
///
/// [google.cloud.universalledger.v1.SubmitTransactionRequest]: <doc:SubmitTransactionRequest>
public struct SignedTransaction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. A serialized
  /// [ClientTransaction][google.cloud.universalledger.v1.ClientTransaction]
  /// with the transaction details.
  ///
  /// [google.cloud.universalledger.v1.ClientTransaction]: <doc:ClientTransaction>
  public var serializedClientTransaction: Foundation.Data = Foundation.Data()

  /// Required. The signature of the transaction sender.
  ///
  /// The signature should be computed by signing the
  /// `serialized_client_transaction` bytes with their own private key.
  ///
  /// For a transaction chain, the bytes to be signed are computed as the
  /// concatenation of:
  /// - A digest of the serialized client transaction of the entire chain.
  /// - A digest of the serialized signed transaction of each unit in the chain,
  ///   in the order they appear in the chain.
  /// The digests are computed using SHA-256.
  public var senderSignature: Foundation.Data = Foundation.Data()

  /// Optional. The key slot of the sender used to sign the transaction. Uses the
  /// primary slot of the sender account if not specified.
  public var senderSigningKeySlot: KeySlot = KeySlot()

  /// Optional. The signatures of accounts listed as additional transaction
  /// signatories. The number and order of these signatures must match the
  /// `signatories` field in the
  /// [ClientTransaction][google.cloud.universalledger.v1.ClientTransaction].
  ///
  /// The bytes to be signed are the same as those for the `sender_signature`,
  /// which each signatory should sign with their own private key.
  ///
  /// The number and identity of additional signatories depends on the particular
  /// transaction kind. For a transaction chain, one signature is needed for each
  /// account appearing either as the sender or as a signatory of a unit in the
  /// chain.
  ///
  /// [google.cloud.universalledger.v1.ClientTransaction]: <doc:ClientTransaction>
  public var otherSignatures: [Foundation.Data] = []

  /// Optional. The key slots of the accounts listed as additional transaction
  /// signatories. If set, the number and order of these key slots must match the
  /// `other_signatures` field in the
  /// [SignedTransaction][google.cloud.universalledger.v1.SignedTransaction].
  /// Defaults to the primary slot of each account if not specified.
  ///
  /// [google.cloud.universalledger.v1.SignedTransaction]: <doc:SignedTransaction>
  public var otherSigningKeySlots: [KeySlot] = []

  /// Initialize a new instance of `SignedTransaction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SignedTransaction().with { $0.serializedClientTransaction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.SignedTransaction"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
