// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A signed query request from the client.
public struct SignedQueryRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. A protobuf serialized
  /// [ClientQuery][google.cloud.universalledger.v1.ClientQuery] to query the
  /// Universal Ledger network.
  ///
  /// [google.cloud.universalledger.v1.ClientQuery]: <doc:ClientQuery>
  public var serializedClientQuery: Foundation.Data = Foundation.Data()

  /// Optional. The signature of the sender of the query request, computed over
  /// the `serialized_client_query` bytes. If this field is omitted, the query is
  /// treated as anonymous, and only public information will be returned.
  ///
  /// The signature is verified by the server only if the sender identifier is
  /// provided in the [ClientQuery][google.cloud.universalledger.v1.ClientQuery].
  /// The signature is rejected if expiry time in the serialized
  /// [ClientQuery][google.cloud.universalledger.v1.ClientQuery] is missing, is
  /// in the past, or more than 5 minutes in the future.
  ///
  /// [google.cloud.universalledger.v1.ClientQuery]: <doc:ClientQuery>
  public var senderSignature: Foundation.Data = Foundation.Data()

  /// Optional. The key slot of the sender used to sign the query request. Uses
  /// the primary slot of the sender account if not specified.
  public var senderSigningKeySlot: KeySlot = KeySlot()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SignedQueryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SignedQueryRequest().with { $0.serializedClientQuery = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serializedClientQuery = CodingKeys(stringValue: "serializedClientQuery")
    static let senderSignature = CodingKeys(stringValue: "senderSignature")
    static let senderSigningKeySlot = CodingKeys(stringValue: "senderSigningKeySlot")

    static let _knownKeys: Set<Swift.String> = [
      "serializedClientQuery",
      "senderSignature",
      "senderSigningKeySlot",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Foundation.Data.self, forKey: .serializedClientQuery)
    {
      self.serializedClientQuery = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .senderSignature) {
      self.senderSignature = value
    }
    if let value = try container.decodeIfPresent(KeySlot.self, forKey: .senderSigningKeySlot) {
      self.senderSigningKeySlot = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.serializedClientQuery, forKey: .serializedClientQuery)
    try container.encode(self.senderSignature, forKey: .senderSignature)
    try container.encode(self.senderSigningKeySlot, forKey: .senderSigningKeySlot)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.SignedQueryRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
