// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response message for SubmitOperationalTransaction.
public struct SubmitOperationalTransactionResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier that uniquely represents the submitted operational transaction.
  /// It is the hexadecimal representation of the SHA-256 digest of the
  /// `serialized_signed_operational_transaction`.
  /// This transaction ID is provided so that a client can track the transaction
  /// without needing to implement the hashing logic itself.
  /// The identifier can be directly used in subsequent API calls, for example to
  /// query the transaction state.
  public var transactionDigestHex: Swift.String = Swift.String()

  /// Initialize a new instance of `SubmitOperationalTransactionResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SubmitOperationalTransactionResponse().with { $0.transactionDigestHex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.universalledger.v1.SubmitOperationalTransactionResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
