// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Certificate of the execution of a specific transaction in a round.
public struct TransactionCertificate: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The ID of the transaction this certificate is for.
  public var transactionDigestHex: Swift.String = Swift.String()

  /// Output only. The ID of the execution round at which this transaction was
  /// executed in.
  public var roundId: Swift.Int64 = Swift.Int64()

  /// Output only. The effects from the transaction execution.
  public var transactionEffects: TransactionEffects? = nil

  /// Output only. Events produced by the transaction.
  public var events: [TransactionEvent] = []

  /// Output only. Homomorphic checksum of the effects. A 2048 byte value encoded
  /// as a hexadecimal string.
  public var transactionEffectsStateChecksumHex: Swift.String = Swift.String()

  /// Output only. The cryptographic digest of all the previous fields in
  /// sequence. Used to build a Merkle tree for the proof of inclusion.
  public var certificationResultsDigestHex: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransactionCertificate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransactionCertificate().with { $0.transactionDigestHex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let transactionDigestHex = CodingKeys(stringValue: "transactionDigestHex")
    static let roundId = CodingKeys(stringValue: "roundId")
    static let transactionEffects = CodingKeys(stringValue: "transactionEffects")
    static let events = CodingKeys(stringValue: "events")
    static let transactionEffectsStateChecksumHex = CodingKeys(
      stringValue: "transactionEffectsStateChecksumHex")
    static let certificationResultsDigestHex = CodingKeys(
      stringValue: "certificationResultsDigestHex")

    static let _knownKeys: Set<Swift.String> = [
      "transactionDigestHex",
      "roundId",
      "transactionEffects",
      "events",
      "transactionEffectsStateChecksumHex",
      "certificationResultsDigestHex",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .transactionDigestHex) {
      self.transactionDigestHex = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .roundId) {
      self.roundId = value
    }
    self.transactionEffects = try container.decodeIfPresent(
      TransactionEffects.self, forKey: .transactionEffects)
    if let value = try container.decodeIfPresent([TransactionEvent].self, forKey: .events) {
      self.events = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .transactionEffectsStateChecksumHex)
    {
      self.transactionEffectsStateChecksumHex = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .certificationResultsDigestHex)
    {
      self.certificationResultsDigestHex = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.transactionDigestHex, forKey: .transactionDigestHex)
    try container.encode(self.roundId, forKey: .roundId)
    try container.encodeIfPresent(self.transactionEffects, forKey: .transactionEffects)
    try container.encode(self.events, forKey: .events)
    try container.encode(
      self.transactionEffectsStateChecksumHex, forKey: .transactionEffectsStateChecksumHex)
    try container.encode(self.certificationResultsDigestHex, forKey: .certificationResultsDigestHex)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.TransactionCertificate"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
