// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Transfers the ownership of the given currency operator to a new account. The
/// sender must be the platform operator.
///
/// If the transaction is successful, deactivates the given currency operator,
/// and the ID of the newly created account is returned as an event in the
/// [TransactionCertificate][google.cloud.universalledger.v1.TransactionCertificate]
/// of the finalized transaction.
///
/// [google.cloud.universalledger.v1.TransactionCertificate]: <doc:TransactionCertificate>
public struct TransferCurrencyOperator: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The public key of the new currency operator. This public key will
  /// be associated with the currency operator and stored on the ledger. It will
  /// be used to validate the signature of the transactions emanating from the
  /// currency operator's account.
  ///
  /// The format of the public key is defined by the `key_format` field.
  /// Considered public information.
  public var publicKey: Foundation.Data = Foundation.Data()

  /// Optional. Immutable. The key format of the public key. If not
  /// specified, defaults to a binary serialized keyset in [Tink wire
  /// format](https://developers.google.com/tink/wire-format#keyset_serialization).
  /// Considered public information.
  public var keyFormat: KeyFormat = KeyFormat()

  /// Optional. Immutable. An opaque comment field that is not interpreted by the
  /// system but stored on the ledger in the account. Considered public
  /// information. Maximum length is 128 characters. May be left empty. Once
  /// created, the field is immutable.
  public var accountComment: Swift.String = Swift.String()

  /// Optional. Deprecated: Use
  /// [currency_operator_id][google.cloud.universalledger.v1.TransferCurrencyOperator.currency_operator_id]
  /// instead. The currency operator to be replaced. Must be active.
  ///
  /// [google.cloud.universalledger.v1.TransferCurrencyOperator.currency_operator_id]: <doc:TransferCurrencyOperator/currencyOperatorId>
  @available(*, deprecated)
  public var currencyOperator: Entity? = nil

  /// Optional. The ID of the currency operator to be replaced. Must be active.
  /// One of `currency_operator` or `currency_operator_id` must be specified. The
  /// value is limited to 60 characters.
  public var currencyOperatorId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferCurrencyOperator`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferCurrencyOperator().with { $0.publicKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let publicKey = CodingKeys(stringValue: "publicKey")
    static let keyFormat = CodingKeys(stringValue: "keyFormat")
    static let accountComment = CodingKeys(stringValue: "accountComment")
    static let currencyOperator = CodingKeys(stringValue: "currencyOperator")
    static let currencyOperatorId = CodingKeys(stringValue: "currencyOperatorId")

    static let _knownKeys: Set<Swift.String> = [
      "publicKey",
      "keyFormat",
      "accountComment",
      "currencyOperator",
      "currencyOperatorId",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .publicKey) {
      self.publicKey = value
    }
    if let value = try container.decodeIfPresent(KeyFormat.self, forKey: .keyFormat) {
      self.keyFormat = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accountComment) {
      self.accountComment = value
    }
    self.currencyOperator = try container.decodeIfPresent(Entity.self, forKey: .currencyOperator)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .currencyOperatorId) {
      self.currencyOperatorId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.publicKey, forKey: .publicKey)
    try container.encode(self.keyFormat, forKey: .keyFormat)
    try container.encode(self.accountComment, forKey: .accountComment)
    try container.encodeIfPresent(self.currencyOperator, forKey: .currencyOperator)
    try container.encode(self.currencyOperatorId, forKey: .currencyOperatorId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.TransferCurrencyOperator"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
