// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Transfers the ownership of the contract token manager to a new account. The
/// sender must be the current currency operator for the currency.
///
/// If the transaction is successful, deactivates the current contract token
/// manager for the currency, and the ID of the newly created account is returned
/// as an event in the
/// [TransactionCertificate][google.cloud.universalledger.v1.TransactionCertificate]
/// of the finalized transaction.
///
/// [google.cloud.universalledger.v1.TransactionCertificate]: <doc:TransactionCertificate>
public struct TransferContractTokenManager: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The public key of the new contract token manager. Note that this
  /// is *not* the public key of the operator. This is the public key of the
  /// *new* contract token manager and it will be stored on the ledger. It will
  /// be used to validate the signature of the transactions emanating from the
  /// contract token manager's account.
  ///
  /// The format of the public key is defined by the `key_format` field.
  /// Considered public information.
  public var publicKey: Foundation.Data = Foundation.Data()

  /// Optional. Immutable. An opaque comment field that is not interpreted by the
  /// system but stored on the ledger in the account. Considered public
  /// information. Maximum length is 128 characters. May be left empty. Once
  /// created, the field is immutable.
  public var accountComment: Swift.String = Swift.String()

  /// Optional. Immutable. The key format of the public key. If not
  /// specified, defaults to a binary serialized keyset in [Tink wire
  /// format](https://developers.google.com/tink/wire-format#keyset_serialization).
  /// Considered public information.
  public var keyFormat: KeyFormat = KeyFormat()

  /// Initialize a new instance of `TransferContractTokenManager`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferContractTokenManager().with { $0.publicKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.TransferContractTokenManager"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
