// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Transfers tokens from one user account to another. The sender must be a
/// regular user account, as opposed to a privileged account like a token manager
/// or an account manager.
///
/// Additionally, the transaction sender must have the `ROLE_PAYER` enabled on
/// it, while the receiver must have the `ROLE_RECEIVER` enabled on it.
public struct Transfer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Deprecated: Use
  /// [beneficiary_id][google.cloud.universalledger.v1.Transfer.beneficiary_id]
  /// instead. The account that receives the tokens.
  ///
  /// [google.cloud.universalledger.v1.Transfer.beneficiary_id]: <doc:Transfer/beneficiaryId>
  @available(*, deprecated)
  public var beneficiary: Entity? = nil

  /// Optional. The ID of the account that receives the tokens. One of
  /// `beneficiary` or `beneficiary_id` must be specified.
  public var beneficiaryId: Swift.String = Swift.String()

  /// Required. The amount to transfer. The amount must be positive.
  public var amount: CurrencyValue? = nil

  /// Initialize a new instance of `Transfer`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Transfer().with { $0.beneficiary = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.Transfer"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
