// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents an update by some transaction to the world state.
///
/// If it has a `delta_val`, it is assumed to be a delta (an integer offset)
/// applied to the previously stored value on a given key. In that case,
/// `new_val` and `old_val` should be empty.
///
/// Otherwise, it is assumed to have at least one of `old_val` or `new_val` (or
/// both). An empty `old_val` indicates the value was inserted. An empty
/// `new_val` indicates the value was deleted.
public struct TransactionEffect: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The key in the world state that was updated.
  public var key: Foundation.Data = Foundation.Data()

  /// Output only. The value of the key before the transaction was executed.
  public var oldVal: Foundation.Data = Foundation.Data()

  /// Output only. The value of the key after the transaction was executed.
  public var newVal: Foundation.Data = Foundation.Data()

  /// Output only. An integer offset that was applied to the previously stored
  /// value.
  public var deltaVal: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `TransactionEffect`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransactionEffect().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.TransactionEffect"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
