// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Certificate of the execution of a specific transaction in a round.
public struct TransactionCertificate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The ID of the transaction this certificate is for.
  public var transactionDigestHex: Swift.String = Swift.String()

  /// Output only. The ID of the execution round at which this transaction was
  /// executed in.
  public var roundId: Swift.Int64 = Swift.Int64()

  /// Output only. The effects of the transaction in the world state.
  public var transactionEffects: TransactionEffects? = nil

  /// Output only. Events produced by the transaction.
  public var events: [TransactionEvent] = []

  /// Output only. Homomorphic checksum of the effects. A 2048 byte value encoded
  /// as a hexadecimal string.
  public var transactionEffectsStateChecksumHex: Swift.String = Swift.String()

  /// Output only. The cryptographic digest of all the previous fields in
  /// sequence. Used to build a Merkle tree for the proof of inclusion.
  public var certificationResultsDigestHex: Swift.String = Swift.String()

  /// Initialize a new instance of `TransactionCertificate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransactionCertificate().with { $0.transactionDigestHex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.TransactionCertificate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
