// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// A service for interacting with the Google Cloud Universal Ledger.
/// Endpoints are pre-created and managed by Google and cannot
/// be modified by users.
/// The names of available endpoints will be provided in the public
/// documentation.
/// An endpoint is a regional resource within a Universal Ledger network.
/// Requests sent to an endpoint may be routed to different validators in the
/// given network within the given region.
///
/// @Snippet(path: "UniversalLedgerQuickstart")
public class UniversalLedgerClient: Clients.UniversalLedgerProtocol {
  let inner: any Clients.UniversalLedgerStub

  /// Creates a new `UniversalLedgerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.UniversalLedgerStub = try Clients.UniversalLedgerTransport(options)
    inner = Clients.UniversalLedgerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.UniversalLedgerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Submits a transaction to the network.
  /// The request is first validated for basic correctness. If validation fails,
  /// the request will fail immediately.
  /// If validation succeeds, this method returns only after the transaction has
  /// been replicated across a majority of validators in the network, or until
  /// the request fails.
  ///
  /// @Snippet(path: "UniversalLedger_SubmitTransaction")
  public func submitTransaction(
    request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse {
    try await self.inner.submitTransaction(request: request, options: options)
  }

  /// Lists all endpoints for a given project and location.
  ///
  /// @Snippet(path: "UniversalLedger_ListEndpoints")
  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse {
    try await self.inner.listEndpoints(request: request, options: options)
  }

  /// Lists all endpoints for a given project and location.
  ///
  /// @Snippet(path: "UniversalLedger_ListEndpoints")
  public func listEndpoints(
    byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEndpoints(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific endpoint.
  ///
  /// @Snippet(path: "UniversalLedger_GetEndpoint")
  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint {
    try await self.inner.getEndpoint(request: request, options: options)
  }

  /// Submits an operational transaction to the network.
  /// This method returns only after the transaction has been replicated across a
  /// majority of validators in the network, or if the transaction fails.
  ///
  /// @Snippet(path: "UniversalLedger_SubmitOperationalTransaction")
  public func submitOperationalTransaction(
    request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse {
    try await self.inner.submitOperationalTransaction(request: request, options: options)
  }

  /// Queries the state of a transaction. This method can be called for any
  /// transaction submitted to the network. The returned transaction details may
  /// vary between calls, because an endpoint may route requests to different
  /// validators within the network and region, and the validators may not be at
  /// the same round ID at any given time.
  ///
  /// @Snippet(path: "UniversalLedger_QueryTransactionState")
  public func queryTransactionState(
    request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse {
    try await self.inner.queryTransactionState(request: request, options: options)
  }

  /// Queries all the information stored about an account in the network.
  /// The returned account details may vary between calls, because an
  /// endpoint may route requests to different validators within the network and
  /// region, and the validators may not be at the same round ID at any given
  /// time.
  ///
  /// @Snippet(path: "UniversalLedger_QueryAccount")
  public func queryAccount(
    request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse {
    try await self.inner.queryAccount(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `UniversalLedgerClient`.
  ///
  /// To mock `UniversalLedgerClient` change your functions to receive
  /// `some UniversalLedgerProtocol` or `any UniversalLedgerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol UniversalLedgerProtocol {
    /// See `UniversalLedgerClient.submitTransaction`.
    func submitTransaction(request: SubmitTransactionRequest) async throws
      -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse

    /// See `UniversalLedgerClient.submitTransaction`.
    func submitTransaction(
      endpoint: Swift.String,
      serializedSignedTransaction: Foundation.Data,
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse

    /// See `UniversalLedgerClient.listEndpoints`.
    func listEndpoints(request: ListEndpointsRequest) async throws
      -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse

    /// See `UniversalLedgerClient.listEndpoints`.
    func listEndpoints(
      byItem: ListEndpointsRequest
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `UniversalLedgerClient.listEndpoints`.
    func listEndpoints(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `UniversalLedgerClient.getEndpoint`.
    func getEndpoint(request: GetEndpointRequest) async throws
      -> GoogleCloudUniversalLedgerV1.Endpoint

    /// See `UniversalLedgerClient.getEndpoint`.
    func getEndpoint(
      name: Swift.String,
    ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint

    /// See `UniversalLedgerClient.submitOperationalTransaction`.
    func submitOperationalTransaction(request: SubmitOperationalTransactionRequest) async throws
      -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse

    /// See `UniversalLedgerClient.submitOperationalTransaction`.
    func submitOperationalTransaction(
      endpoint: Swift.String,
      serializedSignedOperationalTransaction: Foundation.Data,
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse

    /// See `UniversalLedgerClient.queryTransactionState`.
    func queryTransactionState(request: QueryTransactionStateRequest) async throws
      -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse

    /// See `UniversalLedgerClient.queryTransactionState`.
    func queryTransactionState(
      endpoint: Swift.String,
      transactionDigestHex: Swift.String,
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse

    /// See `UniversalLedgerClient.queryAccount`.
    func queryAccount(request: QueryAccountRequest) async throws
      -> GoogleCloudUniversalLedgerV1.QueryAccountResponse

    /// See `UniversalLedgerClient.queryAccount`.
    func queryAccount(
      endpoint: Swift.String,
      accountId: Swift.String,
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse

    /// See `UniversalLedgerClient.submitTransaction`.
    func submitTransaction(
      request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse

    /// See `UniversalLedgerClient.listEndpoints`.
    func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse

    /// See `UniversalLedgerClient.listEndpoints`.
    func listEndpoints(
      byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `UniversalLedgerClient.getEndpoint`.
    func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint

    /// See `UniversalLedgerClient.submitOperationalTransaction`.
    func submitOperationalTransaction(
      request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse

    /// See `UniversalLedgerClient.queryTransactionState`.
    func queryTransactionState(
      request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse

    /// See `UniversalLedgerClient.queryAccount`.
    func queryAccount(
      request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse
  }
}

// Default implementations
extension Clients.UniversalLedgerProtocol {
  public func submitTransaction(request: SubmitTransactionRequest) async throws
    -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse
  {
    try await self.submitTransaction(request: request, options: .init())
  }

  public func submitTransaction(
    request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func submitTransaction(
    endpoint: Swift.String,
    serializedSignedTransaction: Foundation.Data,
  ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse {
    let request = SubmitTransactionRequest().with {
      $0.endpoint = endpoint
      $0.serializedSignedTransaction = serializedSignedTransaction
    }
    return try await self.submitTransaction(request: request)
  }

  public func listEndpoints(request: ListEndpointsRequest) async throws
    -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse
  {
    try await self.listEndpoints(request: request, options: .init())
  }

  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEndpoints(
    byItem: ListEndpointsRequest
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    try self.listEndpoints(byItem: byItem, options: .init())
  }

  public func listEndpoints(
    byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEndpoints(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let request = ListEndpointsRequest().with {
      $0.parent = parent
    }
    return try self.listEndpoints(byItem: request)
  }

  public func getEndpoint(request: GetEndpointRequest) async throws
    -> GoogleCloudUniversalLedgerV1.Endpoint
  {
    try await self.getEndpoint(request: request, options: .init())
  }

  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEndpoint(
    name: Swift.String,
  ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint {
    let request = GetEndpointRequest().with {
      $0.name = name
    }
    return try await self.getEndpoint(request: request)
  }

  public func submitOperationalTransaction(request: SubmitOperationalTransactionRequest)
    async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse
  {
    try await self.submitOperationalTransaction(request: request, options: .init())
  }

  public func submitOperationalTransaction(
    request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func submitOperationalTransaction(
    endpoint: Swift.String,
    serializedSignedOperationalTransaction: Foundation.Data,
  ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse {
    let request = SubmitOperationalTransactionRequest().with {
      $0.endpoint = endpoint
      $0.serializedSignedOperationalTransaction = serializedSignedOperationalTransaction
    }
    return try await self.submitOperationalTransaction(request: request)
  }

  public func queryTransactionState(request: QueryTransactionStateRequest) async throws
    -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse
  {
    try await self.queryTransactionState(request: request, options: .init())
  }

  public func queryTransactionState(
    request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func queryTransactionState(
    endpoint: Swift.String,
    transactionDigestHex: Swift.String,
  ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse {
    let request = QueryTransactionStateRequest().with {
      $0.endpoint = endpoint
      $0.transactionDigestHex = transactionDigestHex
    }
    return try await self.queryTransactionState(request: request)
  }

  public func queryAccount(request: QueryAccountRequest) async throws
    -> GoogleCloudUniversalLedgerV1.QueryAccountResponse
  {
    try await self.queryAccount(request: request, options: .init())
  }

  public func queryAccount(
    request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func queryAccount(
    endpoint: Swift.String,
    accountId: Swift.String,
  ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse {
    let request = QueryAccountRequest().with {
      $0.endpoint = endpoint
      $0.accountId = accountId
    }
    return try await self.queryAccount(request: request)
  }
}
