// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class UniversalLedgerLogging: UniversalLedgerStub {
    let inner: any UniversalLedgerStub
    let logger: Logger

    public init(_ inner: any UniversalLedgerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-universalledger-v1"
      logger[metadataKey: "gcp.client.service"] = "universalledger"
      logger[metadataKey: "gcp.experimental.swift.client"] = "UniversalLedger"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func submitTransaction(
      request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "submitTransaction",
        action: {
          (r: SubmitTransactionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse
          in
          return try await self.inner.submitTransaction(request: r, options: o)
        })
    }

    public func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEndpoints",
        action: {
          (r: ListEndpointsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse
          in
          return try await self.inner.listEndpoints(request: r, options: o)
        })
    }

    public func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEndpoint",
        action: {
          (r: GetEndpointRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.Endpoint
          in
          return try await self.inner.getEndpoint(request: r, options: o)
        })
    }

    public func submitOperationalTransaction(
      request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "submitOperationalTransaction",
        action: {
          (r: SubmitOperationalTransactionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse
          in
          return try await self.inner.submitOperationalTransaction(request: r, options: o)
        })
    }

    public func queryTransactionState(
      request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryTransactionState",
        action: {
          (r: QueryTransactionStateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse
          in
          return try await self.inner.queryTransactionState(request: r, options: o)
        })
    }

    public func queryAccount(
      request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryAccount",
        action: {
          (r: QueryAccountRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.QueryAccountResponse
          in
          return try await self.inner.queryAccount(request: r, options: o)
        })
    }
  }
}
