// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class UniversalLedgerRetry: UniversalLedgerStub {
    let inner: any UniversalLedgerStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any UniversalLedgerStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func submitTransaction(
      request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SubmitTransactionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse
          in
          return try await self.inner.submitTransaction(request: r, options: o)
        })
    }

    public func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEndpointsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse
          in
          return try await self.inner.listEndpoints(request: r, options: o)
        })
    }

    public func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEndpointRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.Endpoint
          in
          return try await self.inner.getEndpoint(request: r, options: o)
        })
    }

    public func submitOperationalTransaction(
      request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SubmitOperationalTransactionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse
          in
          return try await self.inner.submitOperationalTransaction(request: r, options: o)
        })
    }

    public func queryTransactionState(
      request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: QueryTransactionStateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse
          in
          return try await self.inner.queryTransactionState(request: r, options: o)
        })
    }

    public func queryAccount(
      request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: QueryAccountRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudUniversalLedgerV1.QueryAccountResponse
          in
          return try await self.inner.queryAccount(request: r, options: o)
        })
    }
  }
}
