// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol UniversalLedgerStub {
    func submitTransaction(
      request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse

    func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse

    func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint

    func submitOperationalTransaction(
      request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse

    func queryTransactionState(
      request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse

    func queryAccount(
      request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse
  }

  class UniversalLedgerTransport: UniversalLedgerStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://universalledger.googleapis.com")
    }

    public func submitTransaction(
      request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.endpoint as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.endpoint' is not set or is empty")
        }
        return "/v1/\(pathVariable0):submitTransaction"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudUniversalLedgerV1.SubmitTransactionResponse.self, from: data)
    }

    public func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/endpoints"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudUniversalLedgerV1.ListEndpointsResponse.self, from: data)
    }

    public func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudUniversalLedgerV1.Endpoint.self, from: data)
    }

    public func submitOperationalTransaction(
      request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.endpoint as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.endpoint' is not set or is empty")
        }
        return "/v1/\(pathVariable0):submitOperationalTransaction"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse.self, from: data)
    }

    public func queryTransactionState(
      request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.endpoint as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.endpoint' is not set or is empty")
        }
        return "/v1/\(pathVariable0):queryTransactionState"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(
        contentsOf: try encoder.encode(request.transactionDigestHex, prefix: "transactionDigestHex")
      )
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse.self, from: data)
    }

    public func queryAccount(
      request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.endpoint as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.endpoint' is not set or is empty")
        }
        return "/v1/\(pathVariable0):queryAccount"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.accountId, prefix: "accountId"))
      query.append(contentsOf: try encoder.encode(request.roundId, prefix: "roundId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudUniversalLedgerV1.QueryAccountResponse.self, from: data)
    }
  }
}
