// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol UniversalLedgerStub {
    func submitTransaction(
      request: SubmitTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitTransactionResponse

    func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.ListEndpointsResponse

    func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.Endpoint

    func submitOperationalTransaction(
      request: SubmitOperationalTransactionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.SubmitOperationalTransactionResponse

    func queryTransactionState(
      request: QueryTransactionStateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryTransactionStateResponse

    func queryAccount(
      request: QueryAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudUniversalLedgerV1.QueryAccountResponse
  }
}
