// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details specific to a User account.
public struct UserDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Deprecated: Use `account_manager_id` instead.
  /// The account manager for this user.
  @available(*, deprecated)
  public var accountManager: Entity? = nil

  /// Output only. The ID of the account manager for this user.
  public var accountManagerId: Swift.String = Swift.String()

  /// Output only. Deprecated: Use `token_manager_id` instead.
  /// The token manager for this user.
  @available(*, deprecated)
  public var tokenManager: Entity? = nil

  /// Output only. The ID of the token manager for this user.
  public var tokenManagerId: Swift.String = Swift.String()

  /// Output only. The list of roles granted to this account.
  public var roles: [Role] = []

  /// Output only. The status of this account.
  public var accountStatus: AccountStatus = AccountStatus()

  /// Output only. The token balance of this user account.
  public var balance: CurrencyValue? = nil

  /// Output only. Deprecated: Use `contract_account_fields` instead.
  /// The contract account fields (contract ID -> fields) for this user.
  @available(*, deprecated)
  public var accountFields: [Swift.String: Fields] = [:]

  /// Output only. The contract account fields (contract ID -> fields) for this
  /// user.
  public var contractAccountFields: [Swift.String: Fields] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `UserDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserDetails().with { $0.accountManager = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accountManager = CodingKeys(stringValue: "accountManager")
    static let accountManagerId = CodingKeys(stringValue: "accountManagerId")
    static let tokenManager = CodingKeys(stringValue: "tokenManager")
    static let tokenManagerId = CodingKeys(stringValue: "tokenManagerId")
    static let roles = CodingKeys(stringValue: "roles")
    static let accountStatus = CodingKeys(stringValue: "accountStatus")
    static let balance = CodingKeys(stringValue: "balance")
    static let accountFields = CodingKeys(stringValue: "accountFields")
    static let contractAccountFields = CodingKeys(stringValue: "contractAccountFields")

    static let _knownKeys: Set<Swift.String> = [
      "accountManager",
      "accountManagerId",
      "tokenManager",
      "tokenManagerId",
      "roles",
      "accountStatus",
      "balance",
      "accountFields",
      "contractAccountFields",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.accountManager = try container.decodeIfPresent(Entity.self, forKey: .accountManager)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accountManagerId) {
      self.accountManagerId = value
    }
    self.tokenManager = try container.decodeIfPresent(Entity.self, forKey: .tokenManager)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tokenManagerId) {
      self.tokenManagerId = value
    }
    if let value = try container.decodeIfPresent([Role].self, forKey: .roles) {
      self.roles = value
    }
    if let value = try container.decodeIfPresent(AccountStatus.self, forKey: .accountStatus) {
      self.accountStatus = value
    }
    self.balance = try container.decodeIfPresent(CurrencyValue.self, forKey: .balance)
    if let value = try container.decodeIfPresent(
      [Swift.String: Fields].self, forKey: .accountFields)
    {
      self.accountFields = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Fields].self, forKey: .contractAccountFields)
    {
      self.contractAccountFields = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.accountManager, forKey: .accountManager)
    try container.encode(self.accountManagerId, forKey: .accountManagerId)
    try container.encodeIfPresent(self.tokenManager, forKey: .tokenManager)
    try container.encode(self.tokenManagerId, forKey: .tokenManagerId)
    try container.encode(self.roles, forKey: .roles)
    try container.encode(self.accountStatus, forKey: .accountStatus)
    try container.encodeIfPresent(self.balance, forKey: .balance)
    try container.encode(self.accountFields, forKey: .accountFields)
    try container.encode(self.contractAccountFields, forKey: .contractAccountFields)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.UserDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
