// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details specific to a User account.
public struct UserDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Deprecated: Use `account_manager_id` instead.
  /// The account manager for this user.
  @available(*, deprecated)
  public var accountManager: Entity? = nil

  /// Output only. The ID of the account manager for this user.
  public var accountManagerId: Swift.String = Swift.String()

  /// Output only. Deprecated: Use `token_manager_id` instead.
  /// The token manager for this user.
  @available(*, deprecated)
  public var tokenManager: Entity? = nil

  /// Output only. The ID of the token manager for this user.
  public var tokenManagerId: Swift.String = Swift.String()

  /// Output only. The list of roles granted to this account.
  public var roles: [Role] = []

  /// Output only. The status of this account.
  public var accountStatus: AccountStatus = AccountStatus()

  /// Output only. The token balance of this user account.
  public var balance: CurrencyValue? = nil

  /// Output only. Deprecated: Use `contract_account_fields` instead.
  /// The contract account fields (contract ID -> fields) for this user.
  @available(*, deprecated)
  public var accountFields: [Swift.String: Fields] = [:]

  /// Output only. The contract account fields (contract ID -> fields) for this
  /// user.
  public var contractAccountFields: [Swift.String: Fields] = [:]

  /// Initialize a new instance of `UserDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserDetails().with { $0.accountManager = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.UserDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
