// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details specific to a User account.
public struct UserDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The ID of the account manager for this user.
  public var accountManagerId: Swift.String = Swift.String()

  /// Output only. The ID of the token manager for this user.
  public var tokenManagerId: Swift.String = Swift.String()

  /// Output only. The list of roles granted to this account.
  public var roles: [Role] = []

  /// Output only. The status of this account.
  public var accountStatus: AccountStatus = AccountStatus()

  /// Output only. The token balance of this user account.
  public var balance: CurrencyValue? = nil

  /// Output only. The contract account fields (contract ID -> fields) for this
  /// user.
  public var contractAccountFields: [Swift.String: Fields] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UserDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UserDetails().with { $0.accountManagerId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accountManagerId = CodingKeys(stringValue: "accountManagerId")
    static let tokenManagerId = CodingKeys(stringValue: "tokenManagerId")
    static let roles = CodingKeys(stringValue: "roles")
    static let accountStatus = CodingKeys(stringValue: "accountStatus")
    static let balance = CodingKeys(stringValue: "balance")
    static let contractAccountFields = CodingKeys(stringValue: "contractAccountFields")

    static let _knownKeys: Set<Swift.String> = [
      "accountManagerId",
      "tokenManagerId",
      "roles",
      "accountStatus",
      "balance",
      "contractAccountFields",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accountManagerId) {
      self.accountManagerId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tokenManagerId) {
      self.tokenManagerId = value
    }
    if let value = try container.decodeIfPresent([Role].self, forKey: .roles) {
      self.roles = value
    }
    if let value = try container.decodeIfPresent(AccountStatus.self, forKey: .accountStatus) {
      self.accountStatus = value
    }
    self.balance = try container.decodeIfPresent(CurrencyValue.self, forKey: .balance)
    if let value = try container.decodeIfPresent(
      [Swift.String: Fields].self, forKey: .contractAccountFields)
    {
      self.contractAccountFields = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.accountManagerId, forKey: .accountManagerId)
    try container.encode(self.tokenManagerId, forKey: .tokenManagerId)
    try container.encode(self.roles, forKey: .roles)
    try container.encode(self.accountStatus, forKey: .accountStatus)
    try container.encodeIfPresent(self.balance, forKey: .balance)
    try container.encode(self.contractAccountFields, forKey: .contractAccountFields)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `UserDetails`: `"type.googleapis.com/google.cloud.universalledger.v1.UserDetails"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.UserDetails"
  }

  /// Initialize an instance of `UserDetails` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.universalledger.v1.UserDetails"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `UserDetails` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
