// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A concrete value of some type.
public struct Value: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The actual value.
  public var value: OneOf_Value? = nil

  /// Initialize a new instance of `Value`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Value().with { $0.noneValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case noneValue = "noneValue"
    case boolValue = "boolValue"
    case int64Value = "int64Value"
    case stringValue = "stringValue"
    case accountId = "accountId"
    case dictValue = "dictValue"
    case qualifiedCurrencyValue = "qualifiedCurrencyValue"
    case amountValue = "amountValue"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let noneValue = try container.decodeIfPresent(NoneValue.self, forKey: .noneValue) {
      try valueCheckAndSet(.noneValue(noneValue))
    }
    if let boolValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolValue) {
      try valueCheckAndSet(.boolValue(boolValue))
    }
    if let int64Value = try container.decodeIfPresent(Swift.Int64.self, forKey: .int64Value) {
      try valueCheckAndSet(.int64Value(int64Value))
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try valueCheckAndSet(.stringValue(stringValue))
    }
    if let accountId = try container.decodeIfPresent(Swift.String.self, forKey: .accountId) {
      try valueCheckAndSet(.accountId(accountId))
    }
    if let dictValue = try container.decodeIfPresent(DictValue?.self, forKey: .dictValue) {
      try valueCheckAndSet(.dictValue(dictValue))
    }
    if let qualifiedCurrencyValue = try container.decodeIfPresent(
      QualifiedCurrencyValue?.self, forKey: .qualifiedCurrencyValue)
    {
      try valueCheckAndSet(.qualifiedCurrencyValue(qualifiedCurrencyValue))
    }
    if let amountValue = try container.decodeIfPresent(AmountValue?.self, forKey: .amountValue) {
      try valueCheckAndSet(.amountValue(amountValue))
    }
    self.value = value
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.value {
      switch choice {
      case .noneValue(let value):
        try container.encode(value, forKey: .noneValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      case .int64Value(let value):
        try container.encode(value, forKey: .int64Value)
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .accountId(let value):
        try container.encode(value, forKey: .accountId)
      case .dictValue(let value):
        try container.encode(value, forKey: .dictValue)
      case .qualifiedCurrencyValue(let value):
        try container.encode(value, forKey: .qualifiedCurrencyValue)
      case .amountValue(let value):
        try container.encode(value, forKey: .amountValue)
      }
    }
  }

  /// The actual value.
  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// Optional. Represents a None value.
    case noneValue(NoneValue)
    /// Optional. A boolean value.
    case boolValue(Swift.Bool)
    /// Optional. An int64 value.
    case int64Value(Swift.Int64)
    /// Optional. A string value.
    case stringValue(Swift.String)
    /// Optional. An account ID.
    case accountId(Swift.String)
    /// Optional. A dictionary value.
    indirect case dictValue(DictValue?)
    /// Optional. A qualified currency value.
    indirect case qualifiedCurrencyValue(QualifiedCurrencyValue?)
    /// Optional. An amount value.
    indirect case amountValue(AmountValue?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.universalledger.v1.Value"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
